"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
var aa,ba,ca,da,ea,fa,ia;aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};da=ca(this);ea=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
ea("Symbol",function(a){if(a)return a;var b=function(g,h){this.h=g;ba(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.h};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,f=function(g){if(this instanceof f)throw new TypeError("b");return new b(c+(g||"")+"_"+d++,g)};return f});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});fa=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
_.n=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}};_.ha="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}_.ma=ia;
ea("Promise",function(a){function b(){this.h=null}function c(h){return h instanceof f?h:new f(function(k){k(h)})}if(a)return a;b.prototype.j=function(h){if(null==this.h){this.h=[];var k=this;this.m(function(){k.o()})}this.h.push(h)};var d=da.setTimeout;b.prototype.m=function(h){d(h,0)};b.prototype.o=function(){for(;this.h&&this.h.length;){var h=this.h;this.h=[];for(var k=0;k<h.length;++k){var l=h[k];h[k]=null;try{l()}catch(m){this.l(m)}}}this.h=null};b.prototype.l=function(h){this.m(function(){throw h;
})};var f=function(h){this.h=0;this.m=void 0;this.j=[];this.v=!1;var k=this.l();try{h(k.resolve,k.reject)}catch(l){k.reject(l)}};f.prototype.l=function(){function h(m){return function(v){l||(l=!0,m.call(k,v))}}var k=this,l=!1;return{resolve:h(this.F),reject:h(this.o)}};f.prototype.F=function(h){if(h===this)this.o(new TypeError("g"));else if(h instanceof f)this.L(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;default:k=!1}k?this.N(h):this.I(h)}};f.prototype.N=
function(h){var k=void 0;try{k=h.then}catch(l){this.o(l);return}"function"==typeof k?this.R(k,h):this.I(h)};f.prototype.o=function(h){this.A(2,h)};f.prototype.I=function(h){this.A(1,h)};f.prototype.A=function(h,k){if(0!=this.h)throw Error("h`"+h+"`"+k+"`"+this.h);this.h=h;this.m=k;2===this.h&&this.G();this.B()};f.prototype.G=function(){var h=this;d(function(){if(h.fa()){var k=da.console;"undefined"!==typeof k&&k.error(h.m)}},1)};f.prototype.fa=function(){if(this.v)return!1;var h=da.CustomEvent,k=
da.Event,l=da.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof h?h=new h("unhandledrejection",{cancelable:!0}):"function"===typeof k?h=new k("unhandledrejection",{cancelable:!0}):(h=da.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.m;return l(h)};f.prototype.B=function(){if(null!=this.j){for(var h=0;h<this.j.length;++h)g.j(this.j[h]);this.j=null}};var g=new b;f.prototype.L=function(h){var k=this.l();h.Xb(k.resolve,
k.reject)};f.prototype.R=function(h,k){var l=this.l();try{h.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};f.prototype.then=function(h,k){function l(A,w){return"function"==typeof A?function(H){try{m(A(H))}catch(U){v(U)}}:w}var m,v,y=new f(function(A,w){m=A;v=w});this.Xb(l(h,m),l(k,v));return y};f.prototype.catch=function(h){return this.then(void 0,h)};f.prototype.Xb=function(h,k){function l(){switch(m.h){case 1:h(m.m);break;case 2:k(m.m);break;default:throw Error("i`"+m.h);}}var m=this;null==this.j?
g.j(l):this.j.push(l);this.v=!0};f.resolve=c;f.reject=function(h){return new f(function(k,l){l(h)})};f.race=function(h){return new f(function(k,l){for(var m=_.n(h),v=m.next();!v.done;v=m.next())c(v.value).Xb(k,l)})};f.all=function(h){var k=_.n(h),l=k.next();return l.done?c([]):new f(function(m,v){function y(H){return function(U){A[H]=U;w--;0==w&&m(A)}}var A=[],w=0;do A.push(void 0),w++,c(l.value).Xb(y(A.length-1),v),l=k.next();while(!l.done)})};return f});
ea("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var f=d.length,g=0;g<f;g++){var h=d[g];if(b.call(c,h,g,d)){b=h;break a}}b=void 0}return b}});var na=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
ea("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function d(l){if(!na(l,g)){var m=new b;ba(l,g,{value:m})}}function f(l){var m=Object[l];m&&(Object[l]=function(v){if(v instanceof b)return v;Object.isExtensible(v)&&d(v);return m(v)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),v=new a([[l,2],[m,3]]);if(2!=v.get(l)||3!=v.get(m))return!1;v.delete(l);v.set(m,4);return!v.has(l)&&4==v.get(m)}catch(y){return!1}}())return a;
var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0,k=function(l){this.h=(h+=Math.random()+1).toString();if(l){l=_.n(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};k.prototype.set=function(l,m){if(!c(l))throw Error("l");d(l);if(!na(l,g))throw Error("m`"+l);l[g][this.h]=m;return this};k.prototype.get=function(l){return c(l)&&na(l,g)?l[g][this.h]:void 0};k.prototype.has=function(l){return c(l)&&na(l,g)&&na(l[g],this.h)};k.prototype.delete=function(l){return c(l)&&
na(l,g)&&na(l[g],this.h)?delete l[g][this.h]:!1};return k});
ea("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(_.n([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),v=m.next();if(v.done||v.value[0]!=k||"s"!=v.value[1])return!1;v=m.next();return v.done||4!=v.value[0].x||"t"!=v.value[1]||!m.next().done?!1:!0}catch(y){return!1}}())return a;var b=new WeakMap,c=function(k){this.j={};this.h=
g();this.size=0;if(k){k=_.n(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.j[m.id]=[]);m.entry?m.entry.value=l:(m.entry={next:this.h,previous:this.h.previous,head:this.h,key:k,value:l},m.list.push(m.entry),this.h.previous.next=m.entry,this.h.previous=m.entry,this.size++);return this};c.prototype.delete=function(k){k=d(this,k);return k.entry&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.j[k.id],
k.entry.previous.next=k.entry.next,k.entry.next.previous=k.entry.previous,k.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.j={};this.h=this.h.previous=g();this.size=0};c.prototype.has=function(k){return!!d(this,k).entry};c.prototype.get=function(k){return(k=d(this,k).entry)&&k.value};c.prototype.entries=function(){return f(this,function(k){return[k.key,k.value]})};c.prototype.keys=function(){return f(this,function(k){return k.key})};c.prototype.values=function(){return f(this,
function(k){return k.value})};c.prototype.forEach=function(k,l){for(var m=this.entries(),v;!(v=m.next()).done;)v=v.value,k.call(l,v[1],v[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(k,l){var m=l&&typeof l;"object"==m||"function"==m?b.has(l)?m=b.get(l):(m=""+ ++h,b.set(l,m)):m="p_"+l;var v=k.j[m];if(v&&na(k.j,m))for(k=0;k<v.length;k++){var y=v[k];if(l!==l&&y.key!==y.key||l===y.key)return{id:m,list:v,index:k,entry:y}}return{id:m,list:v,index:-1,entry:void 0}},f=function(k,
l){var m=k.h;return fa(function(){if(m){for(;m.head!=k.h;)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},g=function(){var k={};return k.previous=k.next=k.head=k},h=0;return c});var oa=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,f={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f};
ea("Array.prototype.entries",function(a){return a?a:function(){return oa(this,function(b,c){return[b,c]})}});ea("Array.prototype.keys",function(a){return a?a:function(){return oa(this,function(b){return b})}});ea("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});ea("Array.prototype.values",function(a){return a?a:function(){return oa(this,function(b,c){return c})}});
ea("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var f=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var h=0;!(g=b.next()).done;)f.push(c.call(d,g.value,h++))}else for(g=b.length,h=0;h<g;h++)f.push(c.call(d,b[h],h));return f}});var pa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var f in d)na(d,f)&&(a[f]=d[f])}return a};
ea("Object.assign",function(a){return a||pa});ea("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)na(b,d)&&c.push([d,b[d]]);return c}});ea("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});ea("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var f=d.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});
ea("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("j`includes");if(b instanceof RegExp)throw new TypeError("k`includes");return-1!==this.indexOf(b,c||0)}});
ea("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(_.n([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var f=d.entries(),g=f.next();if(g.done||g.value[0]!=c||g.value[1]!=c)return!1;g=f.next();return g.done||g.value[0]==c||4!=g.value[0].x||g.value[1]!=g.value[0]?!1:f.next().done}catch(h){return!1}}())return a;var b=function(c){this.h=new Map;if(c){c=
_.n(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.h.size};b.prototype.add=function(c){c=0===c?0:c;this.h.set(c,c);this.size=this.h.size;return this};b.prototype.delete=function(c){c=this.h.delete(c);this.size=this.h.size;return c};b.prototype.clear=function(){this.h.clear();this.size=0};b.prototype.has=function(c){return this.h.has(c)};b.prototype.entries=function(){return this.h.entries()};b.prototype.values=function(){return this.h.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var f=this;this.h.forEach(function(g){return c.call(d,g,g,f)})};return b});
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.qa=_.qa||{};_.p=this||self;_.sa="closure_uid_"+(1E9*Math.random()>>>0);

}catch(e){_._DumpException(e)}
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.ta=function(){var a=_.p.navigator;return a&&(a=a.userAgent)?a:""};_.q=function(a){return-1!=_.ta().indexOf(a)};_.ua=function(){return _.q("Trident")||_.q("MSIE")};_.va=function(){return _.q("Firefox")||_.q("FxiOS")};_.xa=function(){return _.q("Safari")&&!(_.wa()||_.q("Coast")||_.q("Opera")||_.q("Edge")||_.q("Edg/")||_.q("OPR")||_.va()||_.q("Silk")||_.q("Android"))};_.wa=function(){return(_.q("Chrome")||_.q("CriOS"))&&!_.q("Edge")||_.q("Silk")};
_.ya=function(){return _.q("Android")&&!(_.wa()||_.va()||_.q("Opera")||_.q("Silk"))};_.za=function(){return _.q("iPhone")&&!_.q("iPod")&&!_.q("iPad")};_.Aa=function(){return _.za()||_.q("iPad")||_.q("iPod")};_.Ba=function(){return _.q("Macintosh")};_.Ca=function(){return _.q("Windows")};_.Ea=function(a,b){Object.isFrozen(a)||(_.Da?a[_.Da]|=b:void 0!==a.cc?a.cc|=b:Object.defineProperties(a,{cc:{value:b,configurable:!0,writable:!0,enumerable:!1}}))};_.Fa=function(a){_.Ea(a,1);return a};
_.Ga=function(a){_.p.setTimeout(function(){throw a;},0)};
_.Ha=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
_.Ia=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.r=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)};
_.Ja=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),f="string"===typeof a?a.split(""):a,g=0;g<c;g++)g in f&&(d[g]=b.call(void 0,f[g],g,a));return d};_.Ka=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f="string"===typeof a?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1};
_.La=function(a){_.La[" "](a);return a};_.La[" "]=function(){};
var Ta,Za;_.Ma=_.q("Opera");_.Na=_.ua();_.Oa=_.q("Edge");_.Pa=_.q("Gecko")&&!(-1!=_.ta().toLowerCase().indexOf("webkit")&&!_.q("Edge"))&&!(_.q("Trident")||_.q("MSIE"))&&!_.q("Edge");_.Qa=-1!=_.ta().toLowerCase().indexOf("webkit")&&!_.q("Edge");_.Ra=_.Qa&&_.q("Mobile");Ta=_.p.navigator||null;_.Sa=Ta&&Ta.platform||"";_.Ua=_.Ba();_.Va=_.Ca();_.Wa=_.q("Android");_.Xa=_.za();_.Ya=_.q("iPad");
a:{var $a="",ab=function(){var a=_.ta();if(_.Pa)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.Oa)return/Edge\/([\d\.]+)/.exec(a);if(_.Na)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Qa)return/WebKit\/(\S+)/.exec(a);if(_.Ma)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ab&&($a=ab?ab[1]:"");if(_.Na){var bb,cb=_.p.document;bb=cb?cb.documentMode:void 0;if(null!=bb&&bb>parseFloat($a)){Za=String(bb);break a}}Za=$a}_.db=Za;
_.eb=_.va();_.fb=_.za()||_.q("iPod");_.gb=_.q("iPad");_.hb=_.ya();_.ib=_.wa();_.jb=_.xa()&&!_.Aa();
_.kb="undefined"!==typeof Uint8Array;
_.Da="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;
_.lb=Object.freeze(_.Fa([]));_.mb="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;

}catch(e){_._DumpException(e)}
try{
var vb,yb,Ab,Cb,Db,Eb,Fb,Hb,Jb,Ib,Kb,Lb,Mb,Nb,Ob,Qb,Sb,Zb,ac,bc,dc,hc,kc,lc,mc,pc,tc,wc,yc,Bc,Hc;_.nb=function(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,_.nb);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b);this.h=!0};_.ob=function(){return _.q("CrOS")};
_.pb=function(){var a=_.ta(),b="";_.Ca()?(b=/Windows (?:NT|Phone) ([0-9.]+)/,b=(a=b.exec(a))?a[1]:"0.0"):_.Aa()?(b=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,b=(a=b.exec(a))&&a[1].replace(/_/g,".")):_.Ba()?(b=/Mac OS X ([0-9_.]+)/,b=(a=b.exec(a))?a[1].replace(/_/g,"."):"10"):-1!=_.ta().toLowerCase().indexOf("kaios")?(b=/(?:KaiOS)\/(\S+)/i,b=(a=b.exec(a))&&a[1]):_.q("Android")?(b=/Android\s+([^\);]+)(\)|;)/,b=(a=b.exec(a))&&a[1]):_.ob()&&(b=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,b=(a=b.exec(a))&&a[1]);
return b||""};_.qb=function(a,b){return 0<=(0,_.Ia)(a,b)};_.rb=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.sb=function(a,b){b=(0,_.Ia)(a,b);var c;(c=0<=b)&&_.rb(a,b);return c};_.tb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};vb=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.ub(d)){var f=a.length||0,g=d.length||0;a.length=f+g;for(var h=0;h<g;h++)a[f+h]=d[h]}else a.push(d)}};
yb=function(a){for(var b=0,c=0,d={};c<a.length;){var f=a[c++],g=_.wb(f)?"o"+_.xb(f):(typeof f).charAt(0)+f;Object.prototype.hasOwnProperty.call(d,g)||(d[g]=!0,a[b++]=f)}a.length=b};_.zb=function(a){return _.kb&&null!=a&&a instanceof Uint8Array};Ab=function(a){var b;_.Da?b=a[_.Da]:b=a.cc;return null==b?0:b};_.Bb=function(a){return Array.isArray(a)?!!(Ab(a)&1):!1};Cb=function(a){return Array.isArray(a)?!!(Ab(a)&2):!1};Db=function(a){if(!Array.isArray(a))throw Error("o");_.Ea(a,2)};
Eb=function(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object};Fb=function(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};Hb=function(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)&&_.zb(a))return _.Gb(a)}return a};Jb=function(a,b){if(null!=a){if(Array.isArray(a))a=Ib(a,b);else if(Eb(a)){var c={},d;for(d in a)c[d]=Jb(a[d],b);a=c}else a=b(a);return a}};
Ib=function(a,b){for(var c=a.slice(),d=0;d<c.length;d++)c[d]=Jb(c[d],b);_.Bb(a)&&_.Fa(c);return c};Kb=function(a){return _.zb(a)?new Uint8Array(a):a};Lb=function(a,b){b=void 0===b?Kb:b;return Ib(a,b)};Mb=function(a){return a&&"object"==typeof a&&a.toJSON?a.toJSON():_.zb(a)?new Uint8Array(a):a};Nb=function(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=Hb(a);return Array.isArray(a)?Lb(a,Nb):a};Ob=function(a,b){return Hb(b)};
Qb=function(a,b){b.o&&(a.o=b.o.slice());var c=b.h;if(c){b=b.j;for(var d in c){var f=c[d];if(f){var g=!(!b||!b[d]),h=+d;if(Array.isArray(f)){if(f.length)for(g=_.Pb(a,f[0].constructor,h,g),h=0;h<Math.min(g.length,f.length);h++)Qb(g[h],f[h])}else(g=_.t(a,f.constructor,h,void 0,g))&&Qb(g,f)}}}};_.u=function(a){a&&"function"==typeof a.dispose&&a.dispose()};_.Rb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Sb=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};
_.Tb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.Vb=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<Ub.length;g++)c=Ub[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.x=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(f){c.push("_error_("+f+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Wb("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+Wb(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Wb.apply({},c)))};
_.Yb=function(a,b){_.z.call(this);this.v=b||Xb();this.l=this.h="";this.j=this.m=null;this.A=a;this.o=new _.B(this);_.C(this,this.o);this.o.listen(window,"message",this.B)};Zb=function(a,b,c){_.z.call(this);this.j=a;a=_.D(b,3);b=_.D(b,1);this.h=new _.Yb((0,_.E)(this.m,this),b);this.h.h=a;c&&this.h.Qa(c.origin,c.source);_.C(this,this.h)};ac=function(a,b,c){var d=!1;void 0!==_.D(b,2)?4==_.D(b,2)&&(d=!0):d=_.ib;return d?new $b(a,b,c):new Zb(a,b,c)};bc=function(a){_.z.call(this);this.h=a;this.o=!1};
dc=function(a){bc.call(this,a);this.ka=null;this.j=0;null===cc&&(cc=null)};_.fc=function(){var a=new ec("Google_Hangouts_Chrome");a.Cb(chrome.runtime.id);a.Pa(chrome.runtime.getManifest().version);null==a.h[1]&&(a.h[1]=new dc(a.config));a.h[1].enable();a.Zb().Ed(!1).Cd(100).cd("Script error.",0).enable();a.Wa=a};_.ic=function(a){if(!a.qb){var b;for(b=a.constructor;b&&!b.ib;)b=b.$&&b.$.constructor;b.ib.kd||(b.ib.kd=gc(b));b=new b.ib.kd(a);a.qb=b;a.Hc||(a.Hc=hc)}};hc=function(a){return this.qb.Hc(a)};
_.F=function(a,b){a.prototype=(0,_.ha)(b.prototype);a.prototype.constructor=a;if(_.ma)(0,_.ma)(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.$=b.prototype};_.wb=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.jc=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"};
_.ub=function(a){var b=_.jc(a);return"array"==b||"object"==b&&"number"==typeof a.length};kc=0;_.xb=function(a){return Object.prototype.hasOwnProperty.call(a,_.sa)&&a[_.sa]||(a[_.sa]=++kc)};lc=function(a,b,c){return a.call.apply(a.bind,arguments)};
mc=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(b,f)}}return function(){return a.apply(b,arguments)}};_.E=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.E=lc:_.E=mc;return _.E.apply(null,arguments)};
_.nc=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.oc=function(a,b){a=a.split(".");var c=_.p;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};
_.G=function(a,b){function c(){}c.prototype=b.prototype;a.$=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,f,g){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[f].apply(d,h)}};pc=function(a){return a};_.G(_.nb,Error);_.nb.prototype.name="CustomError";_.qc=function(a,b){return 0==a.lastIndexOf(b,0)};_.rc=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.sc=function(a){return/^[\s\xa0]*$/.test(a)};
tc=function(a,b){return a<b?-1:a>b?1:0};_.uc=function(a,b){var c=0;a=(0,_.Ha)(String(a)).split(".");b=(0,_.Ha)(String(b)).split(".");for(var d=Math.max(a.length,b.length),f=0;0==c&&f<d;f++){var g=a[f]||"",h=b[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;c=tc(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||tc(0==g[2].length,0==h[2].length)||tc(g[2],h[2]);g=g[3];h=h[3]}while(0==c)}return c};
_.vc=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};wc={};_.xc=function(a){return _.vc(wc,a,function(){return 0<=_.uc(_.db,a)})};yc={};_.zc=null;_.Ac=function(){if(!_.zc){_.zc={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));yc[c]=d;for(var f=0;f<d.length;f++){var g=d[f];void 0===_.zc[g]&&(_.zc[g]=f)}}}};
_.Gb=function(a){var b;void 0===b&&(b=0);_.Ac();b=yc[b];for(var c=Array(Math.floor(a.length/3)),d=b[64]||"",f=0,g=0;f<a.length-2;f+=3){var h=a[f],k=a[f+1],l=a[f+2],m=b[h>>2];h=b[(h&3)<<4|k>>4];k=b[(k&15)<<2|l>>6];l=b[l&63];c[g++]=m+h+k+l}m=0;l=d;switch(a.length-f){case 2:m=a[f+1],l=b[(m&15)<<2]||d;case 1:a=a[f],c[g]=b[a>>2]+b[(a&3)<<4|m>>4]+l+d}return c.join("")};_.Cc=function(a){if(Cb(a.Z))throw Error("p");};
_.D=function(a,b,c){return-1===b?null:b>=a.l?a.j?a.j[b]:void 0:(void 0===c?0:c)&&a.j&&(c=a.j[b],null!=c)?c:a.Z[b+a.m]};_.I=function(a,b,c,d,f){d=void 0===d?!1:d;(void 0===f?0:f)||_.Cc(a);b<a.l&&!d?a.Z[b+a.m]=c:(a.j||(a.j=a.Z[a.l+a.m]={}))[b]=c;return a};_.Dc=function(a,b,c,d){c=void 0===c?!0:c;d=void 0===d?!1:d;var f=_.D(a,b,d);null==f&&(f=_.lb);if(Cb(a.Z))c&&(Db(f),Object.freeze(f));else if(f===_.lb||Cb(f))f=_.Fa(f.slice()),_.I(a,b,f,d);return f};_.J=function(a,b){a=_.D(a,b);return null==a?a:!!a};
_.Ec=function(a,b,c){a=_.D(a,b);return null==a?c:a};_.t=function(a,b,c,d,f){if(-1===c)return null;a.h||(a.h={});var g=a.h[c];if(g)return g;f=_.D(a,c,void 0===f?!1:f);if(null==f&&!d)return g;b=new b(f);Cb(a.Z)&&Db(b.Z);return a.h[c]=b};_.Pb=function(a,b,c,d){d=void 0===d?!1:d;a.h||(a.h={});var f=Cb(a.Z),g=a.h[c];if(!g){d=_.Dc(a,c,!0,d);g=[];f=f||Cb(d);for(var h=0;h<d.length;h++)g[h]=new b(d[h]),f&&Db(g[h].Z);f&&(Db(g),Object.freeze(g));a.h[c]=g}return g};
_.K=function(a,b,c){var d=void 0===d?!1:d;_.Cc(a);a.h||(a.h={});var f=c?c.Z:c;a.h[b]=c;return _.I(a,b,f,d)};_.Fc=function(a,b,c){return _.Ec(a,b,void 0===c?"":c)};
Hc=function(a,b,c){a||(a=_.Gc);_.Gc=null;var d=this.constructor.messageId;a||(a=d?[d]:[]);this.m=(d?0:-1)-(this.constructor.h||0);this.h=void 0;this.Z=a;a:{d=this.Z.length;a=d-1;if(d&&(d=this.Z[a],Eb(d))){this.l=a-this.m;this.j=d;break a}void 0!==b&&-1<b?(this.l=Math.max(b,a+1-this.m),this.j=void 0):this.l=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.l)a+=this.m,(d=this.Z[a])?Array.isArray(d)&&_.Fa(d):this.Z[a]=_.lb;else{d=this.j||(this.j=this.Z[this.l+this.m]={});var f=d[a];f?Array.isArray(f)&&
_.Fa(f):d[a]=_.lb}};Hc.prototype.toJSON=function(){var a=this.Z;return Bc?a:Lb(a,Nb)};_.Ic=function(a){Bc=!0;try{return JSON.stringify(a.toJSON(),Ob)}finally{Bc=!1}};Hc.prototype.clone=function(){var a=Lb(this.Z);_.Gc=a;a=new this.constructor(a);_.Gc=null;Qb(a,this);return a};Hc.prototype.toString=function(){return this.Z.toString()};
var Jc=function(){Hc.apply(this,arguments)};_.F(Jc,Hc);if(_.mb){var Kc={};Object.defineProperties(Jc,(Kc[Symbol.hasInstance]=Fb(function(){throw Error("t");}),Kc))}
;_.Lc=Symbol();_.Mc=Symbol();
_.L=function(){Jc.apply(this,arguments)};_.F(_.L,Jc);if(_.mb){var Nc={};Object.defineProperties(_.L,(Nc[Symbol.hasInstance]=Fb(Object[Symbol.hasInstance]),Nc))}
;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.z=function(){this.fa=this.fa;this.I=this.I};_.z.prototype.fa=!1;_.z.prototype.isDisposed=function(){return this.fa};_.z.prototype.dispose=function(){this.fa||(this.fa=!0,this.H())};_.C=function(a,b){_.M(a,_.nc(_.u,b))};_.M=function(a,b,c){a.fa?void 0!==c?b.call(c):b():(a.I||(a.I=[]),a.I.push(void 0!==c?(0,_.E)(b,c):b))};_.z.prototype.H=function(){if(this.I)for(;this.I.length;)this.I.shift()()};
var Oc=function(a,b){this.m=a;this.l=b;this.j=0;this.h=null};Oc.prototype.get=function(){if(0<this.j){this.j--;var a=this.h;this.h=a.next;a.next=null}else a=this.m();return a};var Pc=function(a,b){a.l(b);100>a.j&&(a.j++,b.next=a.h,a.h=b)};
var Uc;_.Qc=[];_.Rc=[];_.Tc=!1;Uc=function(a){_.Qc[_.Qc.length]=a;if(_.Tc)for(var b=0;b<_.Rc.length;b++)a((0,_.E)(_.Rc[b].wrap,_.Rc[b]))};
try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){}
;_.Vc=function(){};
var Ub="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
var Wc;
_.Xc=RegExp("^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)","i");
_.Zc=function(a,b){this.h=b===_.Yc?a:""};_.e=_.Zc.prototype;_.e.wb=!0;_.e.tb=function(){return this.h.toString()};_.e.Nc=!0;_.e.Hb=function(){return 1};_.e.toString=function(){return this.h.toString()};_.Yc={};_.$c=new _.Zc("about:invalid#zClosurez",_.Yc);
var ad;ad={};_.bd=function(a,b,c){this.h=c===ad?a:"";this.j=b;this.wb=this.Nc=!0};_.bd.prototype.Hb=function(){return this.j};_.bd.prototype.tb=function(){return this.h.toString()};_.bd.prototype.toString=function(){return this.h.toString()};_.cd=function(a){if(a instanceof _.bd&&a.constructor===_.bd)return a.h;_.jc(a);return"type_error:SafeHtml"};
_.dd=function(a,b){if(void 0===Wc){var c=null;var d=_.p.trustedTypes;if(d&&d.createPolicy){try{c=d.createPolicy("goog#html",{createHTML:pc,createScript:pc,createScriptURL:pc})}catch(f){_.p.console&&_.p.console.error(f.message)}Wc=c}else Wc=c}a=(c=Wc)?c.createHTML(a):a;return new _.bd(a,b,ad)};_.ed=new _.bd(_.p.trustedTypes&&_.p.trustedTypes.emptyHTML||"",0,ad);_.fd=_.dd("<br>",0);
_.gd=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=_.cd(_.ed);return!b.parentElement});
_.hd=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.id=function(a){return null==a?"":String(a)};
var ld;_.kd=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.jd(c,"*",a,b)[0]||null}return a||null};
_.jd=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var f=0,g=0,h;h=a[g];g++)b==h.nodeName&&(d[f++]=h);d.length=f;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(g=f=0;h=a[g];g++)b=h.className,"function"==typeof b.split&&_.qb(b.split(/\s+/),c)&&(d[f++]=h);d.length=f;return d}return a};
_.md=function(a,b){_.Rb(b,function(c,d){c&&"object"==typeof c&&c.wb&&(c=c.tb());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:ld.hasOwnProperty(d)?a.setAttribute(ld[d],c):_.qc(d,"aria-")||_.qc(d,"data-")?a.setAttribute(d,c):a[d]=c})};ld={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.nd=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};_.od=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.pd=function(a){this.h=a||_.p.document||document};_.pd.prototype.K=function(a){return"string"===typeof a?this.h.getElementById(a):a};_.pd.prototype.setProperties=_.md;_.qd=function(a,b){return _.nd(a.h,b)};
_.pd.prototype.getChildren=function(a){return void 0!=a.children?a.children:Array.prototype.filter.call(a.childNodes,function(b){return 1==b.nodeType})};_.pd.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var sd,td,rd;_.ud=function(a,b){var c=a;b&&(c=(0,_.E)(a,b));c=rd(c);"function"!==typeof _.p.setImmediate||_.p.Window&&_.p.Window.prototype&&!_.q("Edge")&&_.p.Window.prototype.setImmediate==_.p.setImmediate?(sd||(sd=td()),sd(c)):_.p.setImmediate(c)};
td=function(){var a=_.p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.q("Presto")&&(a=function(){var f=_.nd(document,"IFRAME");f.style.display="none";document.documentElement.appendChild(f);var g=f.contentWindow;f=g.document;f.open();f.close();var h="callImmediate"+Math.random(),k="file:"==g.location.protocol?"*":g.location.protocol+"//"+g.location.host;f=(0,_.E)(function(l){if(("*"==k||l.origin==k)&&l.data==h)this.port1.onmessage()},
this);g.addEventListener("message",f,!1);this.port1={};this.port2={postMessage:function(){g.postMessage(h,k)}}});if("undefined"!==typeof a&&!_.ua()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var f=c.hd;c.hd=null;f()}};return function(f){d.next={hd:f};d=d.next;b.port2.postMessage(0)}}return function(f){_.p.setTimeout(f,0)}};rd=function(a){return a};Uc(function(a){rd=a});
var vd=function(){this.j=this.h=null};vd.prototype.add=function(a,b){var c=wd.get();c.set(a,b);this.j?this.j.next=c:this.h=c;this.j=c};vd.prototype.remove=function(){var a=null;this.h&&(a=this.h,this.h=this.h.next,this.h||(this.j=null),a.next=null);return a};var wd=new Oc(function(){return new xd},function(a){return a.reset()}),xd=function(){this.next=this.scope=this.h=null};xd.prototype.set=function(a,b){this.h=a;this.scope=b;this.next=null};
xd.prototype.reset=function(){this.next=this.scope=this.h=null};
var Cd=function(a,b){yd||zd();Ad||(yd(),Ad=!0);Bd.add(a,b)},yd,zd=function(){if(_.p.Promise&&_.p.Promise.resolve){var a=_.p.Promise.resolve(void 0);yd=function(){a.then(Dd)}}else yd=function(){_.ud(Dd)}},Ad=!1,Bd=new vd,Dd=function(){for(var a;a=Bd.remove();){try{a.h.call(a.scope)}catch(b){_.Ga(b)}Pc(wd,a)}Ad=!1};
var Ed=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
var Hd,Id,Jd,Qd,Nd,Ud,Td,Rd,Sd,Wd,Vd,Xd;_.Gd=function(a){this.h=0;this.v=void 0;this.l=this.j=this.m=null;this.o=this.I=!1;if(a!=_.Vc)try{var b=this;a.call(void 0,function(c){_.Fd(b,2,c)},function(c){_.Fd(b,3,c)})}catch(c){_.Fd(this,3,c)}};Hd=function(){this.next=this.m=this.j=this.o=this.h=null;this.l=!1};Hd.prototype.reset=function(){this.m=this.j=this.o=this.h=null;this.l=!1};Id=new Oc(function(){return new Hd},function(a){a.reset()});Jd=function(a,b,c){var d=Id.get();d.o=a;d.j=b;d.m=c;return d};
_.Ld=function(){var a,b,c=new _.Gd(function(d,f){a=d;b=f});return new Kd(c,a,b)};_.Gd.prototype.then=function(a,b,c){return _.Md(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};_.Gd.prototype.$goog_Thenable=!0;_.Od=function(a,b,c){b=Jd(b,b,c);b.l=!0;Nd(a,b)};_.Gd.prototype.cancel=function(a){if(0==this.h){var b=new _.Pd(a);Cd(function(){Qd(this,b)},this)}};
Qd=function(a,b){if(0==a.h)if(a.m){var c=a.m;if(c.j){for(var d=0,f=null,g=null,h=c.j;h&&(h.l||(d++,h.h==a&&(f=h),!(f&&1<d)));h=h.next)f||(g=h);f&&(0==c.h&&1==d?Qd(c,b):(g?(d=g,d.next==c.l&&(c.l=d),d.next=d.next.next):Rd(c),Sd(c,f,3,b)))}a.m=null}else _.Fd(a,3,b)};Nd=function(a,b){a.j||2!=a.h&&3!=a.h||Td(a);a.l?a.l.next=b:a.j=b;a.l=b};
_.Md=function(a,b,c,d){var f=Jd(null,null,null);f.h=new _.Gd(function(g,h){f.o=b?function(k){try{var l=b.call(d,k);g(l)}catch(m){h(m)}}:g;f.j=c?function(k){try{var l=c.call(d,k);void 0===l&&k instanceof _.Pd?h(k):g(l)}catch(m){h(m)}}:h});f.h.m=a;Nd(a,f);return f.h};_.Gd.prototype.B=function(a){this.h=0;_.Fd(this,2,a)};_.Gd.prototype.fa=function(a){this.h=0;_.Fd(this,3,a)};
_.Fd=function(a,b,c){if(0==a.h){a===c&&(b=3,c=new TypeError("w"));a.h=1;a:{var d=c,f=a.B,g=a.fa;if(d instanceof _.Gd){Nd(d,Jd(f||_.Vc,g||null,a));var h=!0}else if(Ed(d))d.then(f,g,a),h=!0;else{if(_.wb(d))try{var k=d.then;if("function"===typeof k){Ud(d,k,f,g,a);h=!0;break a}}catch(l){g.call(a,l);h=!0;break a}h=!1}}h||(a.v=c,a.h=b,a.m=null,Td(a),3!=b||c instanceof _.Pd||Vd(a,c))}};
Ud=function(a,b,c,d,f){var g=!1,h=function(l){g||(g=!0,c.call(f,l))},k=function(l){g||(g=!0,d.call(f,l))};try{b.call(a,h,k)}catch(l){k(l)}};Td=function(a){a.I||(a.I=!0,Cd(a.A,a))};Rd=function(a){var b=null;a.j&&(b=a.j,a.j=b.next,b.next=null);a.j||(a.l=null);return b};_.Gd.prototype.A=function(){for(var a;a=Rd(this);)Sd(this,a,this.h,this.v);this.I=!1};
Sd=function(a,b,c,d){if(3==c&&b.j&&!b.l)for(;a&&a.o;a=a.m)a.o=!1;if(b.h)b.h.m=null,Wd(b,c,d);else try{b.l?b.o.call(b.m):Wd(b,c,d)}catch(f){Xd.call(null,f)}Pc(Id,b)};Wd=function(a,b,c){2==b?a.o.call(a.m,c):a.j&&a.j.call(a.m,c)};Vd=function(a,b){a.o=!0;Cd(function(){a.o&&Xd.call(null,b)})};Xd=_.Ga;_.Pd=function(a){_.nb.call(this,a);this.h=!1};_.G(_.Pd,_.nb);_.Pd.prototype.name="cancel";var Kd=function(a,b,c){this.promise=a;this.resolve=b;this.reject=c};
/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
_.Yd=function(a){this.I=[];this.G=a;this.l=this.F=!1;this.j=void 0;this.B=this.L=this.A=!1;this.v=0;this.h=null;this.o=0};_.Yd.prototype.cancel=function(a){if(this.Ua())this.j instanceof _.Yd&&this.j.cancel();else{if(this.h){var b=this.h;delete this.h;a?b.cancel(a):(b.o--,0>=b.o&&b.cancel())}this.G?this.G.call(null,this):this.B=!0;this.Ua()||this.N(new _.Zd(this))}};_.Yd.prototype.fa=function(a,b){this.A=!1;$d(this,a,b)};
var $d=function(a,b,c){a.F=!0;a.j=c;a.l=!b;ae(a)},ce=function(a){if(a.Ua()){if(!a.B)throw new be(a);a.B=!1}};_.Yd.prototype.callback=function(a){ce(this);$d(this,!0,a)};_.Yd.prototype.N=function(a){ce(this);$d(this,!1,a)};_.ee=function(a,b,c){_.de(a,b,null,c)};_.de=function(a,b,c,d){a.I.push([b,c,d]);a.Ua()&&ae(a)};_.Yd.prototype.then=function(a,b,c){var d,f,g=new _.Gd(function(h,k){f=h;d=k});_.de(this,f,function(h){h instanceof _.Zd?g.cancel():d(h)});return g.then(a,b,c)};
_.Yd.prototype.$goog_Thenable=!0;_.Yd.prototype.m=function(a){var b=new _.Yd;_.de(this,b.callback,b.N,b);a&&(b.h=this,this.o++);return b};_.Yd.prototype.Ua=function(){return this.F};_.Yd.prototype.isError=function(a){return a instanceof Error};
var fe=function(a){return _.Ka(a.I,function(b){return"function"===typeof b[1]})},ae=function(a){if(a.v&&a.Ua()&&fe(a)){var b=a.v,c=ge[b];c&&(_.p.clearTimeout(c.h),delete ge[b]);a.v=0}a.h&&(a.h.o--,delete a.h);b=a.j;for(var d=c=!1;a.I.length&&!a.A;){var f=a.I.shift(),g=f[0],h=f[1];f=f[2];if(g=a.l?h:g)try{var k=g.call(f||null,b);void 0!==k&&(a.l=a.l&&(k==b||a.isError(k)),a.j=b=k);if(Ed(b)||"function"===typeof _.p.Promise&&b instanceof _.p.Promise)d=!0,a.A=!0}catch(l){b=l,a.l=!0,fe(a)||(c=!0)}}a.j=b;
d&&(k=(0,_.E)(a.fa,a,!0),d=(0,_.E)(a.fa,a,!1),b instanceof _.Yd?(_.de(b,k,d),b.L=!0):b.then(k,d));c&&(b=new he(b),ge[b.h]=b,a.v=b.h)},be=function(){_.nb.call(this)};_.G(be,_.nb);be.prototype.message="Deferred has already fired";be.prototype.name="AlreadyCalledError";_.Zd=function(){_.nb.call(this)};_.G(_.Zd,_.nb);_.Zd.prototype.message="Deferred was canceled";_.Zd.prototype.name="CanceledError";var he=function(a){this.h=_.p.setTimeout((0,_.E)(this.m,this),0);this.j=a};
he.prototype.m=function(){delete ge[this.h];throw this.j;};var ge={};
var je,ie,me,ne,le;_.ke=function(a){var b=[];ie(new je,a,b);return b.join("")};je=function(){};
ie=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(Array.isArray(b)){var d=b;b=d.length;c.push("[");for(var f="",g=0;g<b;g++)c.push(f),ie(a,d[g],c),f=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(g=b[d],"function"!=typeof g&&(c.push(f),le(d,c),c.push(":"),ie(a,g,c),f=","));c.push("}");return}}switch(typeof b){case "string":le(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("x`"+typeof b);}}};me={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\v":"\\u000b"};ne=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;le=function(a,b){b.push('"',a.replace(ne,function(c){var d=me[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).slice(1),me[c]=d);return d}),'"')};
_.pe=function(a,b){this.type="function"==typeof _.oe&&a instanceof _.oe?String(a):a;this.h=this.target=b;this.defaultPrevented=this.m=!1};_.pe.prototype.l=function(){this.m=!0};_.pe.prototype.j=function(){this.defaultPrevented=!0};
var qe=function(){if(!_.p.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{_.p.addEventListener("test",function(){},b),_.p.removeEventListener("test",function(){},b)}catch(c){}return a}();
var re=function(a,b){_.pe.call(this,a?a.type:"");this.relatedTarget=this.h=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.va=null;a&&this.init(a,b)};_.G(re,_.pe);var se={2:"touch",3:"pen",4:"mouse"};
re.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.h=b;if(b=a.relatedTarget){if(_.Pa){a:{try{_.La(b.nodeName);var f=!0;break a}catch(g){}f=!1}f||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||
0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:se[a.pointerType]||"";this.state=a.state;this.va=a;a.defaultPrevented&&re.$.j.call(this)};
re.prototype.l=function(){re.$.l.call(this);this.va.stopPropagation?this.va.stopPropagation():this.va.cancelBubble=!0};re.prototype.j=function(){re.$.j.call(this);var a=this.va;a.preventDefault?a.preventDefault():a.returnValue=!1};
var te;te="closure_listenable_"+(1E6*Math.random()|0);_.ue=function(a){return!(!a||!a[te])};
var ve=0;
var we=function(a,b,c,d,f){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.ac=f;this.key=++ve;this.removed=this.Wb=!1},xe=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.ac=null};
var ye=function(a){this.src=a;this.h={};this.j=0},Ce,ze;ye.prototype.add=function(a,b,c,d,f){var g=a.toString();a=this.h[g];a||(a=this.h[g]=[],this.j++);var h=ze(a,b,d,f);-1<h?(b=a[h],c||(b.Wb=!1)):(b=new we(b,this.src,g,!!d,f),b.Wb=c,a.push(b));return b};ye.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.h))return!1;var f=this.h[a];b=ze(f,b,c,d);return-1<b?(xe(f[b]),_.rb(f,b),0==f.length&&(delete this.h[a],this.j--),!0):!1};
var Ae=function(a,b){var c=b.type;c in a.h&&_.sb(a.h[c],b)&&(xe(b),0==a.h[c].length&&(delete a.h[c],a.j--))};ye.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.h)if(!a||c==a){for(var d=this.h[c],f=0;f<d.length;f++)++b,xe(d[f]);delete this.h[c];this.j--}return b};_.Be=function(a,b,c,d,f){a=a.h[b.toString()];b=-1;a&&(b=ze(a,c,d,f));return-1<b?a[b]:null};Ce=function(a){return Sb(a.h,function(b){for(var c=0;c<b.length;)return!0;return!1})};
ze=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.removed&&g.listener==b&&g.capture==!!c&&g.ac==d)return f}return-1};
var De,Ee,Fe,Je,Le,Me,Ne,Qe;De="closure_lm_"+(1E6*Math.random()|0);Ee={};Fe=0;_.He=function(a,b,c,d,f){if(d&&d.once)return _.Ge(a,b,c,d,f);if(Array.isArray(b)){for(var g=0;g<b.length;g++)_.He(a,b[g],c,d,f);return null}c=_.Ie(c);return _.ue(a)?a.listen(b,c,_.wb(d)?!!d.capture:!!d,f):Je(a,b,c,!1,d,f)};
Je=function(a,b,c,d,f,g){if(!b)throw Error("y");var h=_.wb(f)?!!f.capture:!!f,k=_.Ke(a);k||(a[De]=k=new ye(a));c=k.add(b,c,d,h,g);if(c.proxy)return c;d=Le();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)qe||(f=h),void 0===f&&(f=!1),a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(Me(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("z");Fe++;return c};Le=function(){var a=Ne,b=function(c){return a.call(b.src,b.listener,c)};return b};
_.Ge=function(a,b,c,d,f){if(Array.isArray(b)){for(var g=0;g<b.length;g++)_.Ge(a,b[g],c,d,f);return null}c=_.Ie(c);return _.ue(a)?a.Vb(b,c,_.wb(d)?!!d.capture:!!d,f):Je(a,b,c,!0,d,f)};_.Oe=function(a,b,c,d,f){if(Array.isArray(b))for(var g=0;g<b.length;g++)_.Oe(a,b[g],c,d,f);else d=_.wb(d)?!!d.capture:!!d,c=_.Ie(c),_.ue(a)?a.m.remove(String(b),c,d,f):a&&(a=_.Ke(a))&&(b=_.Be(a,b,c,d,f))&&_.Pe(b)};
_.Pe=function(a){if("number"!==typeof a&&a&&!a.removed){var b=a.src;if(_.ue(b))Ae(b.m,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Me(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Fe--;(c=_.Ke(b))?(Ae(c,a),0==c.j&&(c.src=null,b[De]=null)):xe(a)}}};Me=function(a){return a in Ee?Ee[a]:Ee[a]="on"+a};Ne=function(a,b){if(a.removed)a=!0;else{b=new re(b,this);var c=a.listener,d=a.ac||a.src;a.Wb&&_.Pe(a);a=c.call(d,b)}return a};
_.Ke=function(a){a=a[De];return a instanceof ye?a:null};Qe="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Ie=function(a){if("function"===typeof a)return a;a[Qe]||(a[Qe]=function(b){return a.handleEvent(b)});return a[Qe]};Uc(function(a){Ne=a(Ne)});
_.N=function(){_.z.call(this);this.m=new ye(this);this.cb=this;this.N=null};_.G(_.N,_.z);_.N.prototype[te]=!0;_.e=_.N.prototype;_.e.addEventListener=function(a,b,c,d){_.He(this,a,b,c,d)};_.e.removeEventListener=function(a,b,c,d){_.Oe(this,a,b,c,d)};
_.e.dispatchEvent=function(a){var b,c=this.N;if(c)for(b=[];c;c=c.N)b.push(c);c=this.cb;var d=a.type||a;if("string"===typeof a)a=new _.pe(a,c);else if(a instanceof _.pe)a.target=a.target||c;else{var f=a;a=new _.pe(d,c);_.Vb(a,f)}f=!0;if(b)for(var g=b.length-1;!a.m&&0<=g;g--){var h=a.h=b[g];f=h.rb(d,!0,a)&&f}a.m||(h=a.h=c,f=h.rb(d,!0,a)&&f,a.m||(f=h.rb(d,!1,a)&&f));if(b)for(g=0;!a.m&&g<b.length;g++)h=a.h=b[g],f=h.rb(d,!1,a)&&f;return f};
_.e.H=function(){_.N.$.H.call(this);this.m&&this.m.removeAll(void 0);this.N=null};_.e.listen=function(a,b,c,d){return this.m.add(String(a),b,!1,c,d)};_.e.Vb=function(a,b,c,d){return this.m.add(String(a),b,!0,c,d)};_.e.rb=function(a,b,c){a=this.m.h[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,f=0;f<a.length;++f){var g=a[f];if(g&&!g.removed&&g.capture==b){var h=g.listener,k=g.ac||g.src;g.Wb&&Ae(this.m,g);d=!1!==h.call(k,c)&&d}}return d&&!c.defaultPrevented};
var Re=function(){};Re.prototype.h=null;var Te=function(a){var b;(b=a.h)||(b={},Se(a)&&(b[0]=!0,b[1]=!0),b=a.h=b);return b};
var Ue,Ve=function(){};_.G(Ve,Re);var We=function(a){return(a=Se(a))?new ActiveXObject(a):new XMLHttpRequest},Se=function(a){if(!a.j&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.j=d}catch(f){}}throw Error("A");}return a.j};Ue=new Ve;
_.Xe=function(a,b){_.N.call(this);this.j=a||1;this.h=b||_.p;this.l=(0,_.E)(this.af,this);this.o=Date.now()};_.G(_.Xe,_.N);_.e=_.Xe.prototype;_.e.enabled=!1;_.e.Aa=null;_.e.setInterval=function(a){this.j=a;this.Aa&&this.enabled?(this.stop(),this.start()):this.Aa&&this.stop()};
_.e.af=function(){if(this.enabled){var a=Date.now()-this.o;0<a&&a<.8*this.j?this.Aa=this.h.setTimeout(this.l,this.j-a):(this.Aa&&(this.h.clearTimeout(this.Aa),this.Aa=null),this.dispatchEvent("tick"),this.enabled&&(this.stop(),this.start()))}};_.e.start=function(){this.enabled=!0;this.Aa||(this.Aa=this.h.setTimeout(this.l,this.j),this.o=Date.now())};_.e.stop=function(){this.enabled=!1;this.Aa&&(this.h.clearTimeout(this.Aa),this.Aa=null)};_.e.H=function(){_.Xe.$.H.call(this);this.stop();delete this.h};
_.Ye=function(a,b,c){if("function"===typeof a)c&&(a=(0,_.E)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.E)(a.handleEvent,a);else throw Error("B");return 2147483647<Number(b)?-1:_.p.setTimeout(a,b||0)};_.Ze=function(a){_.p.clearTimeout(a)};
var $e=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),af=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(0<=d){var g=a[c].substring(0,d);f=a[c].substring(d+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};
var bf=function(a){_.N.call(this);this.headers=new Map;this.F=a||null;this.j=!1;this.B=this.h=null;this.R="";this.l=this.L=this.o=this.G=!1;this.A=0;this.v=null;this.ha="";this.da=this.aa=!1},cf,df,ef,mf,lf,hf;_.G(bf,_.N);cf=/^https?$/i;df=["POST","PUT"];ef=[];_.ff=function(a,b,c,d,f,g,h){var k=new bf;ef.push(k);b&&k.listen("complete",b);k.Vb("ready",k.sa);g&&(k.A=Math.max(0,g));h&&(k.aa=h);k.send(a,c,d,f)};bf.prototype.sa=function(){this.dispose();_.sb(ef,this)};
bf.prototype.send=function(a,b,c,d){if(this.h)throw Error("C`"+this.R+"`"+a);b=b?b.toUpperCase():"GET";this.R=a;this.G=!1;this.j=!0;this.h=this.F?We(this.F):We(Ue);this.B=this.F?Te(this.F):Te(Ue);this.h.onreadystatechange=(0,_.E)(this.ga,this);try{this.L=!0,this.h.open(b,String(a),!0),this.L=!1}catch(h){gf(this);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var f in d)c.set(f,d[f]);else if("function"===typeof d.keys&&"function"===typeof d.get){f=_.n(d.keys());
for(var g=f.next();!g.done;g=f.next())g=g.value,c.set(g,d.get(g))}else throw Error("D`"+String(d));d=Array.from(c.keys()).find(function(h){return"content-type"==h.toLowerCase()});f=_.p.FormData&&a instanceof _.p.FormData;!_.qb(df,b)||d||f||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=_.n(c);for(d=b.next();!d.done;d=b.next())c=_.n(d.value),d=c.next().value,c=c.next().value,this.h.setRequestHeader(d,c);this.ha&&(this.h.responseType=this.ha);"withCredentials"in this.h&&this.h.withCredentials!==
this.aa&&(this.h.withCredentials=this.aa);try{hf(this),0<this.A&&((this.da=jf(this.h))?(this.h.timeout=this.A,this.h.ontimeout=(0,_.E)(this.ea,this)):this.v=_.Ye(this.ea,this.A,this)),this.o=!0,this.h.send(a),this.o=!1}catch(h){gf(this)}};var jf=function(a){return _.Na&&_.xc(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout};bf.prototype.ea=function(){"undefined"!=typeof _.qa&&this.h&&(this.dispatchEvent("timeout"),this.abort(8))};
var gf=function(a){a.j=!1;a.h&&(a.l=!0,a.h.abort(),a.l=!1);kf(a);lf(a)},kf=function(a){a.G||(a.G=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};bf.prototype.abort=function(){this.h&&this.j&&(this.j=!1,this.l=!0,this.h.abort(),this.l=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),lf(this))};bf.prototype.H=function(){this.h&&(this.j&&(this.j=!1,this.l=!0,this.h.abort(),this.l=!1),lf(this,!0));bf.$.H.call(this)};
bf.prototype.ga=function(){this.isDisposed()||(this.L||this.o||this.l?mf(this):this.X())};bf.prototype.X=function(){mf(this)};mf=function(a){if(a.j&&"undefined"!=typeof _.qa&&(!a.B[1]||4!=(a.h?a.h.readyState:0)||2!=a.J()))if(a.o&&4==(a.h?a.h.readyState:0))_.Ye(a.ga,0,a);else if(a.dispatchEvent("readystatechange"),4==(a.h?a.h.readyState:0)){a.j=!1;try{_.nf(a)?(a.dispatchEvent("complete"),a.dispatchEvent("success")):kf(a)}finally{lf(a)}}};
lf=function(a,b){if(a.h){hf(a);var c=a.h,d=a.B[0]?function(){}:null;a.h=null;a.B=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(f){}}};hf=function(a){a.h&&a.da&&(a.h.ontimeout=null);a.v&&(_.Ze(a.v),a.v=null)};
_.nf=function(a){var b=a.J();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.R).match($e)[1]||null,!a&&_.p.self&&_.p.self.location&&(a=_.p.self.location.protocol.slice(0,-1)),b=!cf.test(a?a.toLowerCase():"");c=b}return c};bf.prototype.J=function(){try{return 2<(this.h?this.h.readyState:0)?this.h.status:-1}catch(a){return-1}};_.of=function(a){try{return a.h?a.h.responseText:""}catch(b){return""}};
Uc(function(a){bf.prototype.X=a(bf.prototype.X)});
var qf;_.B=function(a){_.z.call(this);this.da=a;this.v={}};_.G(_.B,_.z);var pf=[];_.B.prototype.listen=function(a,b,c,d){Array.isArray(b)||(b&&(pf[0]=b.toString()),b=pf);for(var f=0;f<b.length;f++){var g=_.He(a,b[f],c||this.handleEvent,d||!1,this.da||this);if(!g)break;this.v[g.key]=g}return this};_.rf=function(a,b,c,d){qf(a,b,c,d)};qf=function(a,b,c,d,f,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)qf(a,b,c[h],d,f,g);else(b=_.Ge(b,c,d||a.handleEvent,f,g||a.da||a))&&(a.v[b.key]=b)};
_.B.prototype.removeAll=function(){_.Rb(this.v,function(a,b){this.v.hasOwnProperty(b)&&_.Pe(a)},this);this.v={}};_.B.prototype.H=function(){_.B.$.H.call(this);this.removeAll()};_.B.prototype.handleEvent=function(){throw Error("E");};
_.sf=function(){};_.sf.prototype.next=function(){return _.tf};_.tf={done:!0,value:void 0};_.sf.prototype.Ea=function(){return this};
var uf;_.yf=function(a){if(a instanceof uf||a instanceof vf||a instanceof wf)return a;if("function"==typeof a.next)return new uf(function(){return a});if("function"==typeof a[Symbol.iterator])return new uf(function(){return a[Symbol.iterator]()});if("function"==typeof a.Ea)return new uf(function(){return a.Ea()});throw Error("F");};uf=function(a){this.j=a};uf.prototype.Ea=function(){return new vf(this.j())};uf.prototype[Symbol.iterator]=function(){return new wf(this.j())};uf.prototype.h=function(){return new wf(this.j())};
var vf=function(a){this.j=a};_.F(vf,_.sf);vf.prototype.next=function(){return this.j.next()};vf.prototype[Symbol.iterator]=function(){return new wf(this.j)};vf.prototype.h=function(){return new wf(this.j)};var wf=function(a){uf.call(this,function(){return a});this.m=a};_.F(wf,uf);wf.prototype.next=function(){return this.m.next()};
_.zf=function(a){_.L.call(this,a)};_.F(_.zf,_.L);_.zf.messageId="uv_r_hrd";
_.Af=function(a){_.L.call(this,a)};_.F(_.Af,_.L);
var Wb=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("G");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(f,g,h,k,l,m,v,y){if("%"==m)return"%";var A=c.shift();if("undefined"==typeof A)throw Error("H");arguments[0]=A;return Bf[m].apply(null,arguments)})},Bf={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+(0,_.hd)(" ",Number(c)-a.length):(0,_.hd)(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,f){d=a.toString();isNaN(f)||""==f||(d=parseFloat(a).toFixed(f));var g=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=g+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(f)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(f);a=Number(c)-d.length-g.length;return d=0<=b.indexOf("-",0)?g+d+(0,_.hd)(" ",a):g+(0,_.hd)(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,f,g,h,k){return Bf.f(parseInt(a,10),b,c,d,0,g,h,k)}};Bf.i=Bf.d;Bf.u=Bf.d;
var Cf=function(a,b){this.h=a;this.j=b};Cf.prototype.execute=function(a){this.h&&(this.h.call(this.j||null,a),this.h=this.j=null)};Cf.prototype.abort=function(){this.j=this.h=null};Uc(function(a){Cf.prototype.execute=a(Cf.prototype.execute)});
_.O=function(a,b){var c=c||[];this.m=a;this.j=b||null;this.h=[];this.h=this.h.concat(c)};_.O.prototype.toString=function(){return this.m};
_.Ef=function(a){_.L.call(this,a,-1,Df)};_.F(_.Ef,_.L);var Df=[2];_.Ef.messageId="h_exts";
var Ff,Gf,Hf,Jf,Lf,Uf,Mf,Of,Nf,Rf,Pf,Kf,Vf;_.P=function(a){this.j=this.v=this.o="";this.l=null;this.A=this.h="";this.I=!1;var b;a instanceof _.P?(this.I=a.I,Ff(this,a.o),this.v=a.v,this.j=a.j,Gf(this,a.l),this.h=a.h,Hf(this,a.m.clone()),_.If(this,a.A)):a&&(b=String(a).match($e))?(this.I=!1,Ff(this,b[1]||"",!0),this.v=Jf(b[2]||""),this.j=Jf(b[3]||"",!0),Gf(this,b[4]),this.h=Jf(b[5]||"",!0),Hf(this,b[6]||"",!0),_.If(this,b[7]||"",!0)):(this.I=!1,this.m=new Kf(null,this.I))};
_.P.prototype.toString=function(){var a=[],b=this.o;b&&a.push(Lf(b,Mf,!0),":");var c=this.j;if(c||"file"==b)a.push("//"),(b=this.v)&&a.push(Lf(b,Mf,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.l,null!=c&&a.push(":",String(c));if(c=this.h)this.j&&"/"!=c.charAt(0)&&a.push("/"),a.push(Lf(c,"/"==c.charAt(0)?Nf:Of,!0));(c=this.m.toString())&&a.push("?",c);(c=this.A)&&a.push("#",Lf(c,Pf));return a.join("")};
_.P.prototype.resolve=function(a){var b=this.clone(),c=!!a.o;c?Ff(b,a.o):c=!!a.v;c?b.v=a.v:c=!!a.j;c?b.j=a.j:c=null!=a.l;var d=a.h;if(c)Gf(b,a.l);else if(c=!!a.h){if("/"!=d.charAt(0))if(this.j&&!this.h)d="/"+d;else{var f=b.h.lastIndexOf("/");-1!=f&&(d=b.h.slice(0,f+1)+d)}f=d;if(".."==f||"."==f)d="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){d=_.qc(f,"/");f=f.split("/");for(var g=[],h=0;h<f.length;){var k=f[h++];"."==k?d&&h==f.length&&g.push(""):".."==k?((1<g.length||1==g.length&&""!=g[0])&&
g.pop(),d&&h==f.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=f}c?b.h=d:c=""!==a.m.toString();c?Hf(b,a.m.clone()):c=!!a.A;c&&_.If(b,a.A);return b};_.P.prototype.clone=function(){return new _.P(this)};Ff=function(a,b,c){a.o=c?Jf(b,!0):b;a.o&&(a.o=a.o.replace(/:$/,""))};Gf=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("J`"+b);a.l=b}else a.l=null};Hf=function(a,b,c){b instanceof Kf?(a.m=b,Qf(a.m,a.I)):(c||(b=Lf(b,Rf)),a.m=new Kf(b,a.I))};_.Q=function(a,b,c){a.m.set(b,c)};
_.If=function(a,b,c){a.A=c?Jf(b):b};_.Sf=function(a){return a instanceof _.P?a.clone():new _.P(a)};_.Tf=function(a,b){a instanceof _.P||(a=_.Sf(a));b instanceof _.P||(b=_.Sf(b));return a.resolve(b)};Jf=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""};Lf=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Uf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Uf=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};
Mf=/[#\/\?@]/g;Of=/[#\?:]/g;Nf=/[#\?]/g;Rf=/[#\?@]/g;Pf=/#/g;Kf=function(a,b){this.j=this.h=null;this.m=a||null;this.l=!!b};Vf=function(a){a.h||(a.h=new Map,a.j=0,a.m&&af(a.m,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};Kf.prototype.add=function(a,b){Vf(this);this.m=null;a=Wf(this,a);var c=this.h.get(a);c||this.h.set(a,c=[]);c.push(b);this.j+=1;return this};
Kf.prototype.remove=function(a){Vf(this);a=Wf(this,a);return this.h.has(a)?(this.m=null,this.j-=this.h.get(a).length,this.h.delete(a)):!1};Kf.prototype.clear=function(){this.h=this.m=null;this.j=0};var Xf=function(a,b){Vf(a);b=Wf(a,b);return a.h.has(b)};_.e=Kf.prototype;_.e.forEach=function(a,b){Vf(this);this.h.forEach(function(c,d){c.forEach(function(f){a.call(b,f,d,this)},this)},this)};
_.e.Ta=function(){Vf(this);for(var a=Array.from(this.h.values()),b=Array.from(this.h.keys()),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};_.e.pa=function(a){Vf(this);var b=[];if("string"===typeof a)Xf(this,a)&&(b=b.concat(this.h.get(Wf(this,a))));else{a=Array.from(this.h.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};_.e.set=function(a,b){Vf(this);this.m=null;a=Wf(this,a);Xf(this,a)&&(this.j-=this.h.get(a).length);this.h.set(a,[b]);this.j+=1;return this};
_.e.get=function(a,b){if(!a)return b;a=this.pa(a);return 0<a.length?String(a[0]):b};_.Yf=function(a,b,c){a.remove(b);0<c.length&&(a.m=null,a.h.set(Wf(a,b),_.tb(c)),a.j+=c.length)};Kf.prototype.toString=function(){if(this.m)return this.m;if(!this.h)return"";for(var a=[],b=Array.from(this.h.keys()),c=0;c<b.length;c++){var d=b[c],f=encodeURIComponent(String(d));d=this.pa(d);for(var g=0;g<d.length;g++){var h=f;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}}return this.m=a.join("&")};
Kf.prototype.clone=function(){var a=new Kf;a.m=this.m;this.h&&(a.h=new Map(this.h),a.j=this.j);return a};var Wf=function(a,b){b=String(b);a.l&&(b=b.toLowerCase());return b},Qf=function(a,b){b&&!a.l&&(Vf(a),a.m=null,a.h.forEach(function(c,d){var f=d.toLowerCase();d!=f&&(this.remove(d),_.Yf(this,f,c))},a));a.l=b};
var Zf;Zf=function(a){return(a=a.exec(_.ta()))?a[1]:""};_.$f=function(){if(_.eb)return Zf(/Firefox\/([0-9.]+)/);if(_.Na||_.Oa||_.Ma)return _.db;if(_.ib){if(_.Aa()||_.Ba()){var a=Zf(/CriOS\/([0-9.]+)/);if(a)return a}return Zf(/Chrome\/([0-9.]+)/)}if(_.jb&&!_.Aa())return Zf(/Version\/([0-9.]+)/);if(_.fb||_.gb){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.ta()))return a[1]+"."+a[2]}else if(_.hb)return(a=Zf(/Android\s+([0-9.]+)/))?a:Zf(/Version\/([0-9.]+)/);return""}();
_.ag=function(a){this.h=a||{cookie:""}};_.e=_.ag.prototype;
_.e.set=function(a,b,c){var d=!1;if("object"===typeof c){var f=c.Tf;d=c.secure||!1;var g=c.domain||void 0;var h=c.path||void 0;var k=c.Ae}if(/[;=\s]/.test(a))throw Error("L`"+a);if(/[;\r\n]/.test(b))throw Error("M`"+b);void 0===k&&(k=-1);this.h.cookie=a+"="+b+(g?";domain="+g:"")+(h?";path="+h:"")+(0>k?"":0==k?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*k)).toUTCString())+(d?";secure":"")+(null!=f?";samesite="+f:"")};
_.e.get=function(a,b){for(var c=a+"=",d=(this.h.cookie||"").split(";"),f=0,g;f<d.length;f++){g=(0,_.Ha)(d[f]);if(0==g.lastIndexOf(c,0))return g.slice(c.length);if(g==a)return""}return b};_.e.remove=function(a,b,c){var d=void 0!==this.get(a);this.set(a,"",{Ae:0,path:b,domain:c});return d};_.e.Ta=function(){return bg(this).keys};_.e.pa=function(){return bg(this).values};_.e.clear=function(){for(var a=bg(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
var bg=function(a){a=(a.h.cookie||"").split(";");for(var b=[],c=[],d,f,g=0;g<a.length;g++)f=(0,_.Ha)(a[g]),d=f.indexOf("="),-1==d?(b.push(""),c.push(f)):(b.push(f.substring(0,d)),c.push(f.substring(d+1)));return{keys:b,values:c}};
var cg=function(a,b){_.pe.call(this,a,b);this.msg=b};_.F(cg,_.pe);
var dg=function(a){_.L.call(this,a)};_.F(dg,_.L);var eg=function(a,b){return _.I(a,1,b)};
var fg=function(a){_.L.call(this,a)};_.F(fg,_.L);var gg=function(a,b){return _.I(a,1,b)},hg=function(a,b){return _.I(a,2,b)},ig=function(a,b){return _.I(a,3,b)};fg.messageId="capi_md1571";
var Xb=function(){for(var a=10,b=jg,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},jg="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
_.G(_.Yb,_.z);_.Yb.prototype.Qa=function(a,b,c){this.l=a;this.m=b;this.j=c};
_.Yb.prototype.B=function(a){a=a.va;var b=a.origin;this.m&&this.m!=a.source||"*"!=this.l&&this.l!=b?b=!1:this.j?(b=(new _.P(b)).j,b=_.rc(b,this.j)?b.length==this.j.length||"."==this.j[0]||"."==b[b.length-1-this.j.length]:!1):b=!0;if(b&&(b=a.data)&&"string"===typeof b&&"["==b[0]){try{var c=JSON.parse(b);if(!Array.isArray(c))return}catch(d){return}if(0!=c.length&&c[0]==fg.messageId&&(c=new fg(c),_.D(c,1)==this.v)){b=_.D(c,3);if(!this.h)this.h=b;else if(this.h!=b)return;"*"!=this.l&&this.m||this.Qa(a.origin,
a.source);1==_.D(c,2)?this.send(2):this.A(c,a)}}};_.Yb.prototype.send=function(a,b,c){if(this.h&&this.m){var d=_.Ic(hg(gg(ig(b||new fg,this.v),this.h),a)),f=this.m,g=this.l;_.Na?_.Ye(function(){f.postMessage(d,g)}):c?f.postMessage(d,g,c):f.postMessage(d,g)}};
var kg=function(a,b,c,d){this.m=_.Ld();this.h=new _.Yb((0,_.E)(this.o,this),c);this.h.Qa("*",a,d);this.h.h=b;this.j=new _.Xe(50);this.j.start();_.He(this.j,"tick",this.l,!1,this);this.l();_.Od(this.m.promise,this.I,this)};kg.prototype.I=function(){_.u(this.h);_.Oe(this.j,"tick",this.l,!1,this);_.u(this.j)};kg.prototype.l=function(){this.h.send(1)};kg.prototype.o=function(a,b){2==_.D(a,2)&&this.m.resolve(b.origin)};
_.G(Zb,_.z);Zb.prototype.send=function(a){var b=new fg;a=_.K(b,4,a);this.h.send(0,a)};Zb.prototype.connect=function(a,b){this.h.Qa(a,b);this.h.send(3)};Zb.prototype.m=function(a){0==_.D(a,2)&&(a=_.t(a,dg,4),this.j(a))};Zb.prototype.l=function(){};
var $b=function(a,b,c){_.z.call(this);this.o=a;this.j=this.h=this.m=null;c?(this.j=c.ports[0],lg(this)):(this.h=new _.Yb(function(){},_.D(b,1)),this.h.h=_.D(b,3))};_.F($b,_.z);$b.prototype.H=function(){_.z.prototype.H.call(this);this.j&&this.j.close();_.u(this.h)};$b.prototype.l=function(){this.m=new _.B(this);_.C(this,this.m);lg(this)};$b.prototype.send=function(a){this.j.postMessage(a.toJSON())};
$b.prototype.connect=function(a,b){var c=new MessageChannel;this.j=c.port1;lg(this);var d=this.h;this.h=null;c=c.port2;d.Qa(a,b);d.send(4,void 0,[c]);_.u(d)};var lg=function(a){a.j&&a.m&&(a.m.listen(a.j,"message",a.v),a.j.start())};$b.prototype.v=function(a){a=a.va;try{var b=new dg(a.data)}catch(c){return}this.o(b)};
var qg,sg;_.mg=function(){_.N.call(this);this.v=null;this.A=!1;this.o=[];this.l=[];_.M(this,this.F,this);this.j=null};_.F(_.mg,_.N);_.mg.prototype.F=function(){for(;this.l.length;)this.l.shift()()};_.og=function(a){a.F();a.o=[];a.j=new _.Yd;a.l.push((0,_.E)(a.j.cancel,a.j));a.A=!1;_.ee(a.j.m(),function(b){(Ce(this.m)||this.N)&&_.ng(this);this.l.push(_.nc(_.u,b))},a)};_.mg.prototype.sendMessage=function(a){pg(this,Lb(a.Z,Mb))};var pg=function(a,b){if(a.j){var c=eg(new dg,b);_.ee(a.j.m(),function(d){d.send(c)})}};
_.mg.prototype.V=function(){return this};_.mg.prototype.Qa=function(a,b,c){this.h.Qa(a,b,c)};_.rg=function(a,b,c,d){_.og(a);qg(a,b,c,d).then(function(f){var g=ig(gg(new fg,f.bf),c);g=ac((0,_.E)(this.B,this),g);g.connect(f.origin,b);this.j.callback(g)},void 0,a)};qg=function(a,b,c,d){var f=Xb();b=(new kg(b,c,f,d)).m.promise;a.l.push((0,_.E)(b.cancel,b));return b.then(function(g){return{bf:f,origin:g}})};
_.mg.prototype.L=function(a,b){if(3==_.D(a,2)||4==_.D(a,2))_.u(this.h),this.h=null,this.j.callback(ac((0,_.E)(this.B,this),a,b))};_.mg.prototype.B=function(a){this.o.push(a);this.G()};_.mg.prototype.G=function(){for(;sg(this););};sg=function(a){if(a.isDisposed()||!a.A||0==a.o.length)return!1;var b=_.D(a.o.shift(),1);a.v&&pg(a.v,b);a.dispatchEvent(new cg(b[0],b));return!0};_.ng=function(a){a.A||(a.A=!0,a.j&&_.ee(a.j.m(),function(b){b.l();_.Ye(this.G,0,this)},a))};
_.mg.prototype.listen=function(a,b,c,d){_.ng(this);return _.N.prototype.listen.call(this,a,b,c,d)};_.mg.prototype.Vb=function(a,b,c,d){_.ng(this);return _.N.prototype.Vb.call(this,a,b,c,d)};
var tg=function(a){this.j=a;this.l="empty";this.h=null;this.m={}};tg.prototype.getContext=function(){return this.m};tg.prototype.Pa=function(a){this.l=a;return this};tg.prototype.Cb=function(a){this.h=a;return this};tg.prototype.Sc=function(a){this.m=_.Tb(a);return this};
var ug=function(){};
var vg=function(){};_.G(vg,ug);vg.prototype[Symbol.iterator]=function(){return _.yf(this.Ea(!0)).h()};vg.prototype.clear=function(){var a=Array.from(this);a=_.n(a);for(var b=a.next();!b.done;b=a.next())this.remove(b.value)};
var wg=function(a){this.h=a};_.G(wg,vg);_.e=wg.prototype;_.e.isAvailable=function(){if(!this.h)return!1;try{return this.h.setItem("__sak","1"),this.h.removeItem("__sak"),!0}catch(a){return!1}};_.e.set=function(a,b){try{this.h.setItem(a,b)}catch(c){if(0==this.h.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.e.get=function(a){a=this.h.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};
_.e.remove=function(a){this.h.removeItem(a)};_.e.Ea=function(a){var b=0,c=this.h,d=new _.sf;d.next=function(){if(b>=c.length)return _.tf;var f=c.key(b++);if(a)return{value:f,done:!1};f=c.getItem(f);if("string"!==typeof f)throw"Storage mechanism: Invalid value was encountered";return{value:f,done:!1}};return d};_.e.clear=function(){this.h.clear()};_.e.key=function(a){return this.h.key(a)};
var xg=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.h=a};_.G(xg,wg);
var Ag=function(a,b){this.m=a;this.h=[];null===yg&&(yg=null);this.j=null;b&&(this.j=new xg);if(null!=this.j&&this.j.isAvailable()&&(a=this.j.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.h=JSON.parse(a)||[]}catch(c){}a=!1;Array.isArray(this.h)||(this.h=[],a=!0);for(;this.h.length>this.m;)this.h.shift(),a=!0;a&&zg(this)},zg=function(a){if(null!=a.j&&a.j.isAvailable())try{a.j.set("__webmonitoring_RateThrottler_history_hourlyRate",_.ke(a.h))}catch(b){}},yg=null;
_.G(bc,_.z);bc.prototype.setEnabled=function(a){this.o=a};
var Bg=function(a){bc.call(this,a);this.N=100;this.B={};this.ka=null;this.m="";this.F=!0;this.v=10;this.j=null;this.l=!1};_.F(Bg,bc);_.e=Bg.prototype;_.e.Ed=function(a){this.F=a;return this};_.e.Ze=function(a){this.v=Math.min(a,100);return this};_.e.Cd=function(a){this.N=a;return this};_.e.cd=function(a,b){this.B[a]=b;return this};_.e.Bd=function(a){this.ka=a;return this};_.e.Ye=function(a){this.m=a;return this};
_.e.enable=function(){if(this.o)return!1;this.A=window.onerror;window.onerror=this.Oe.bind(this);this.setEnabled(!0);return!0};
_.e.yd=function(a,b,c,d,f,g){g=void 0===g?new Map:g;var h=_.Sf(window.location.href);a=null!=f&&null!=f.message?f.message:a;var k;if(k="function"!==typeof this.ka||this.ka(h.h,a,b,c,d,f))if(k=this.l){k=Object.keys(this.B);for(var l=100,m=0;m<k.length;++m){var v=k[m];(new RegExp(v)).test(a)&&(l=this.B[v])}if(k=(100*Math.random()).toFixed(6)>=this.N*l/100?!1:!0){0<=this.v&&null===this.j&&(this.j=new Ag(this.v,this.F));if(null===this.j)k=!1;else{a:{k=this.j;l=Date.now();if(k.h.length==k.m)if(k.h[0]<
l-36E5)k.h.shift();else{k=!1;break a}k.h.push(l);zg(k);k=!0}k=!k}k=!k&&this.l}}k&&(f=f||null,b=Cg(this,h,a,g,b,c,void 0!==d?d:null),b.prod=this.h.j,b.ver=this.h.l,c=null!==f?_.id(f.stack):"",b=Dg(b),_.sc(a)||(d=c.split("\n"),-1<d[0].indexOf(a)&&(d.splice(0,1),c=d.join("\n"))),Eg(this,"https://clients2.google.com/cr/staging_report",b,c),h={product:this.h.j,url:h.h,js_errors_count:"1"},a=_.id(this.h.h),_.sc(a)||(h.version=a),Eg(this,"https://clients2.google.com/cr/staging_perf",Dg(h)))};
_.e.Oe=function(a,b,c,d,f){this.yd(a,b,c,d,f);null!=this.A&&"function"===typeof this.A&&this.A(a,b,c,d,f)};
var Cg=function(a,b,c,d,f,g,h){var k=_.Tb(a.h.getContext());d.forEach(function(l,m){k[m]=l});k.url=b.h;k.type="JavascriptError";k.error_message=c;k.browser=Fg();k.browser_version=_.$f;k.os=_.ob()?"Chrome OS":_.q("Linux")?"Linux":_.Ca()?"Windows":_.q("Android")?"Android":_.za()?"iPhone":_.q("iPad")?"iPad":_.q("iPod")?"iPod":_.Ba()?"Mac":"Unknown";k.os_version=_.pb();b=a.h.h;null!==b&&(k.channel=b);_.sc(a.m)||(k.guid=a.m);null!==f&&(k.src=f);null!==g&&(k.line=g.toString());null!==h&&(k.column=h.toString());
return k},Dg=function(a){var b="",c;for(c in a)b+=_.sc(b)?"?":"&",b+=c+"="+encodeURIComponent(a[c]);return b},Eg=function(a,b,c,d){d=d||"";var f=_.sc(d)?{}:{"Content-Type":"text/plain"};_.ff(b+c,a.G.bind(a,b),"POST",d,f,6E4,!0)};Bg.prototype.G=function(a,b){_.nf(b.target)};var Fg=function(){var a="Other";_.Ma?a="Opera":_.Na?a="Internet Explorer":_.eb?a="Firefox":_.ib?a="Chrome":_.jb&&(a="Safari");return a};Bg.prototype.reportError=Bg.prototype.yd;Bg.prototype.enable=Bg.prototype.enable;
Bg.prototype.setClientId=Bg.prototype.Ye;Bg.prototype.setCallback=Bg.prototype.Bd;Bg.prototype.addPerErrorMessageSampling=Bg.prototype.cd;Bg.prototype.setGlobalSampling=Bg.prototype.Cd;Bg.prototype.setMaxErrorsPerHour=Bg.prototype.Ze;Bg.prototype.setUseLocalStorage=Bg.prototype.Ed;
_.G(dc,bc);dc.prototype.Bd=function(a){this.ka=a;return this};var Gg=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];dc.prototype.enable=function(){if(this.o)return!1;if(window.performance&&window.performance.memory){var a=new _.Xe(6E4);_.C(this,a);var b=new _.B(this);_.C(this,b);b.listen(a,"tick",this.m);a.start();this.setEnabled(!0);return!0}return!1};
dc.prototype.m=function(){this.j+=6E4;for(var a="",b=0;b<Gg.length;++b)if(this.j==Gg[b].age){a=Gg[b].name;break}if(""!=a){b=Hg.test(_.ta())?"":"32_bit_";var c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}];b=_.Sf(window.location.href).h;
c="?product="+encodeURIComponent(this.h.j)+"&url="+encodeURIComponent(b);var d=_.id(this.h.h);_.sc(d)||(c+="&version="+encodeURIComponent(d));for(d=0;d<a.length;++d)c+="&"+encodeURIComponent(a[d].name)+"="+a[d].value,"function"===typeof this.ka&&this.ka(b,a[d].displayName,a[d].value);_.ff("https://clients2.google.com/cr/staging_perf"+c,Ig,"POST","",null,6E4,!0)}}};var Ig=function(a){_.nf(a.target)},Hg=/(x86_64|Win64)/,cc=null;
var Jg=function(a){_.z.call(this);this.config=new tg(a);this.h={}};_.G(Jg,_.z);_.oc("webmonitoring.Monitoring",Jg);Jg.prototype.Pa=function(a){this.config.Pa(a);return this};Jg.prototype.setVersion=Jg.prototype.Pa;Jg.prototype.Cb=function(a){this.config.Cb(a);return this};Jg.prototype.setChannel=Jg.prototype.Cb;Jg.prototype.Sc=function(a){this.config.Sc(a);return this};Jg.prototype.setContext=Jg.prototype.Sc;Jg.prototype.getContext=function(){return this.config.getContext()};
Jg.prototype.Zb=function(){null==this.h[2]&&(this.h[2]=new Bg(this.config));return this.h[2]};Jg.prototype.createJsErrorsReporter=Jg.prototype.Zb;
var ec=function(a){Jg.call(this,a)};_.F(ec,Jg);ec.prototype.Pa=function(a){return Jg.prototype.Pa.call(this,a)};ec.prototype.Cb=function(a){return Jg.prototype.Cb.call(this,a)};ec.prototype.Zb=function(){var a=Jg.prototype.Zb.call(this);a.l=!0;return a};
var gc,Ng,Lg,Mg,Og;_.Kg=function(){};gc=function(a){var b=a.ib,c=function(l){c.$.constructor.call(this,l);var m=this.ua.length;this.h=[];for(var v=0;v<m;++v)this.ua[v].Lf||(this.h[v]=new this.ua[v](l))};_.G(c,b);for(var d=[];a&&a!==Object;){if(b=a.ib){b.ua&&(vb(d,b.ua),yb(d));var f=b.prototype,g;for(g in f)if(f.hasOwnProperty(g)&&"function"===typeof f[g]&&f[g]!==b){var h=!!f[g].fe,k=Lg(g,f,d,h);(h=Mg(g,f,k,h))&&(c.prototype[g]=h)}}a=Ng(a)}c.prototype.ua=d;return c};
Ng=function(a){return a===Object?Object:Object.getPrototypeOf?Object.getPrototypeOf(a.prototype).constructor||Object:a.$&&a.$.constructor||Object};Lg=function(a,b,c,d){for(var f=[],g=0;g<c.length&&(c[g].prototype[a]===b[a]||(f.push(g),!d));++g);return f};
Mg=function(a,b,c,d){var f;c.length?f=d?function(g){var h=this.h[c[0]];return h?h[a].apply(this.h[c[0]],arguments):this.ua[c[0]].prototype[a].apply(this,arguments)}:b[a].he?function(g){a:{var h=Array.prototype.slice.call(arguments,0);for(var k=0;k<c.length;++k){var l=this.h[c[k]];if(l=l?l[a].apply(l,h):this.ua[c[k]].prototype[a].apply(this,h)){h=l;break a}}h=!1}return h}:b[a].ge?function(g){a:{var h=Array.prototype.slice.call(arguments,0);for(var k=0;k<c.length;++k){var l=this.h[c[k]];l=l?l[a].apply(l,
h):this.ua[c[k]].prototype[a].apply(this,h);if(null!=l){h=l;break a}}h=void 0}return h}:b[a].vd?function(g){for(var h=Array.prototype.slice.call(arguments,0),k=0;k<c.length;++k){var l=this.h[c[k]];l?l[a].apply(l,h):this.ua[c[k]].prototype[a].apply(this,h)}}:function(g){for(var h=Array.prototype.slice.call(arguments,0),k=[],l=0;l<c.length;++l){var m=this.h[c[l]];k.push(m?m[a].apply(m,h):this.ua[c[l]].prototype[a].apply(this,h))}return k}:d||b[a].he||b[a].ge||b[a].vd?f=null:f=Og;return f};Og=function(){return[]};
_.Kg.prototype.Hc=function(a){if(this.h)for(var b=0;b<this.h.length;++b)if(this.h[b]instanceof a)return this.h[b];return null};

}catch(e){_._DumpException(e)}
try{
var wv=function(a){return Array.prototype.concat.apply([],arguments)},xv=function(){},yv=function(a){var b=_.Tf(_.D(a,2),"/webchat/extension-start");_.D(a,5)&&_.Q(b,"e",_.D(a,5));return new _.Gd(function(c,d){_.ff(b,function(f){_.nf(f.target)||d();try{var g=JSON.parse(_.of(f.target));c(new _.Ef(g))}catch(h){d(h.message)}})})},zv=function(a,b){_.Md(a,null,b)},Av=function(a,b){return a.m.get(b)},Bv=function(a,b){a.v=b;_.M(a,function(){this.v=null},a);_.ng(a)},Cv=function(a,b,c){a=_.J(a,b);return null==
a?void 0===c?!1:c:a},Dv=function(a){var b=new _.mg;_.og(b);b.h=new _.Yb((0,_.E)(b.L,b),a);b.h.Qa("*");b.l.push(_.nc(_.u,b.h));return b},Ev=function(a){(a?a:function(){}).fe=!0},Fv=function(a){this.h=a;_.Na||(delete this.h.lpu,delete this.h.ppu)},Gv=function(a,b){var c={};c.cn=Math.floor(2147483648*Math.random()).toString(36);c.tp=1;c.ifrid=b;c.pu=a;return new Fv(c)},Hv=["cn","tp"];_.oc("GTalk_IFrameChannelConfig.build",Gv);
_.G(xv,_.Kg);xv.prototype.j=function(a){return a};Ev(xv.prototype.j);xv.prototype.m=function(){return!0};Ev(xv.prototype.m);
var Iv=function(a){_.L.call(this,a)};_.F(Iv,_.L);
var Jv=function(a,b){var c=new Iv;b=_.I(c,1,b);return _.I(b,2,a)},Kv=Jv("?",0),Lv=Jv("q",1),Mv=Jv("<",2),Nv=Jv(">",3),Ov=Jv("~",4),Pv=Jv("s",5),Qv={mf:Kv,wf:Lv,pf:Mv,qf:Nv,nf:Ov,xf:Pv};
var Rv=function(a){_.L.call(this,a)};_.F(Rv,_.L);Rv.messageId="ci:ec";
var Sv=function(a){_.L.call(this,a)};_.F(Sv,_.L);var Tv=function(a){_.L.call(this,a)};_.F(Tv,_.L);var Uv=function(a){_.L.call(this,a)};_.F(Uv,_.L);var Vv=function(a){_.L.call(this,a)};_.F(Vv,_.L);var Wv=function(a){_.L.call(this,a)};_.F(Wv,_.L);Sv.messageId="h_cc";
var Xv=function(a,b){_.ic(this);var c=this.qb.j(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.qc(c,"https://talkgadget.google.com/talkgadget/")){var d=(new _.ag(window.document)).get("WCSDBG","");d=d.split(";")[0];d=d.split("|")[0];var f=["plus.google.com"],g=RegExp("^[-_a-zA-Z0-9\\.]+\\.talkgadget\\.google\\.com$");0<d.length&&!_.qb(f,d)&&g.test(d)&&(c=_.Sf(c),c=_.Sf("https://"+d+c.h).toString())}this.j=c;this.m=b||new Rv;a.notificationsOnly&&_.I(this.m,1,!0);this.authUser="0";
null!=a.authUser?this.authUser=a.authUser:(b=Av(new _.P(window.location.href),"authuser"),null!=b&&(this.authUser=b));this.v=a.clientUrl||"notifierclient";b=Av(_.Sf(this.v),"authuser");null!=b&&(this.authUser=b);this.vc=a.propertyName||"Google Talk";this.B=a.cssUrl;this.locale=a.locale;this.o=a.debug;this.Ub=a.userJid;this.gb=a.uiVersion;this.we=null!=a.rosterExpanded?a.rosterExpanded:!0;this.ea=a.hostLogMinValue;this.eb=a.hideChat;this.Gc=a.refresh;this.R=a.hideProfileCard;this.aa=a.hideStatusMsgs;
this.da=a.hideRosterOptions;this.X=a.hideRecentConversations;this.L=a.hideOTR;this.zc=a.hostServerMessageCallback||!1;this.ha=a.isCentralRoster;this.Ec=a.isFullFrame||!1;this.Mc=a.rosterClass||"talk_roster";this.xe=a.rosterId||"talk_roster";this.h="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.h=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.cb=a.parentToken;void 0!==a.isRtl||_.Xc.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=
[];for(var h in Qv)b.push(Qv[h].toJSON())}this.N=a.entityId;this.Jb=a.useQuasarPanels||!1;this.silent=a.silent||!1;this.Bc=a.ignoreCentralRoster||!1;this.Kc=a.lazy||!1;this.yc=a.handleProfileLinks||!1;this.ga=a.hostSettings;this.I=a.screen;this.fa=a.docsConfig;this.Ic=a.jsmode;this.Da=a.moleWidth;this.Ba=a.moleHeight;this.sa=a.minimizedMoleHeight||36;this.ye=a.derp;this.fb=window.location.protocol+"//"+window.location.host;this.l="";this.G=a.optOutAllowed;this.F=a.legacyTalkSignedIn;this.Kb=a.useSpareMole;
this.A=a.conversationId};xv.$||_.G(xv,_.Kg);Xv.ib=xv;new _.O("du37De");
var Zv=function(a){var b={},c=_.Fc(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.D(a,2)&&27!=_.D(a,2)&&(d="http://"));b.clientBaseUrl=d+c+"/webchat/u/"+_.Fc(a,8,"0")+"/";b.clientUrl="load";b.authUser=_.Fc(a,8,"0");b.propertyName=Yv(_.D(a,2));b.locale=_.D(a,4);b.hideProfileCard=!0;b.parentToken=_.D(a,3);b.isRtl=Cv(a,6,!1);b.lazy=Cv(a,7,!1);b.entityId=_.D(a,9);b.hostSettings=_.D(a,5);b.jsmode=_.D(a,11);b.isFullFrame=Cv(a,13,!1);b.rosterId=_.Fc(a,12,"talk_roster");
b.rosterIframeId=_.Fc(a,12,"talk_roster");b.rosterIframeIdB=_.Fc(a,15,"gtn-roster-iframe-id-b");b.derp=!!Cv(a,16,!1);c=_.t(a,Wv,14);null!=c&&(b.isCentralRoster=Cv(c,1,!1),b.useQuasarPanels=Cv(c,2,!1));c=_.t(a,Tv,10);null!=c&&(b.moleManagerLeftMargin=_.D(c,1),b.moleManagerMiddleMargin=_.D(c,2),b.moleManagerRightMargin=_.D(c,3),b.moleManagerNoMoleAreaMargin=_.D(c,4),b.moleManagerBoundingElementId=_.D(c,5),b.moleWidth=_.D(c,6),b.moleHeight=_.D(c,7),b.minimizedMoleHeight=_.D(c,8));c=_.t(a,Uv,18);null!=
c&&(b.optOutAllowed=Cv(c,1,!0),d=_.t(c,Vv,3),null!=d&&(b.legacyTalkSignedIn=Cv(d,1,!0)),c=_.J(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new Rv;c=_.I(c,2,!0);c=_.I(c,1,!0);c=_.I(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=Cv(a,17,!1);b.conversationId=_.D(a,19);return b},Yv=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";
case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 27:return"ChromeApp";case 36:return"StartPage"}},$v=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.Sf(a),d=c.h;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.h="/u/"+b+d;return c.toString()}return a};
var aw=function(a,b,c,d,f){_.z.call(this);this.h=a;this.j=d||window.document;this.m=new _.B(this);_.C(this,this.m);var g=_.ta();d=new _.P(a.j+a.v);Cv(a.m,2,!1)||(_.Q(d,"ts","0"),_.Q(d,"re",a.we),_.Q(d,"ref",a.Gc));_.Q(d,"client","sm");_.Q(d,"prop",a.vc);_.Q(d,"nav","true");_.Q(d,"fid",a.h);a.o&&_.Q(d,"debug",a.o);_.Q(d,"os",_.Sa);_.Q(d,"stime",c);a.eb&&_.Q(d,"hc",a.eb);for(c=0;c<Hv.length;++c);b=_.ke(b.h);_.Q(d,"xpc",b);_.Q(d,"ec",_.ke(a.m.toJSON()));a.I&&_.Q(d,"screen",a.I);-1!=g.indexOf("MSIE")&&
_.Q(d,"ua",g);a.cb&&_.Q(d,"pvt",a.cb);a.zc&&_.Q(d,"hsmc","true");void 0!==a.ea&&_.Q(d,"logl",a.ea);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.Q(d,"href",b.join("?")));b=new _.P(window.location.href);"false"==Av(b,"uacheck")&&_.Q(d,"uacheck",!1);(g=a.Ic)&&_.Q(d,"jsmode",g);(g=Av(b,"cssmode"))&&_.Q(d,"cssmode",g);(g=Av(b,"convid"))&&_.Q(d,"convid",g);if(g=b.m.pa("convp"))Array.isArray(g)||(g=[String(g)]),_.Yf(d.m,"convp",g);(g=Av(b,
"smexp"))&&_.Q(d,"smexp",g);g=b.m.pa("mods");a.Kc&&g.push("lazy");f&&(g=wv(g,f));0<g.length&&_.Q(d,"mods",g.join(","));if(!a.j||0>a.j.indexOf("/u/"))(f=Av(b,"authuser"))?_.Q(d,"authuser",f):null!=a.authUser&&_.Q(d,"authuser",a.authUser);f=Av(b,"eid");_.sc(_.id(f))||_.Q(d,"eid",f);_.sc(_.id(this.h.N))||_.Q(d,"eid",this.h.N);null!=this.h.position&&_.Q(d,"pos",this.h.position);void 0!==a.gb&&_.Q(d,"uiv",this.h.gb);a.B&&_.Q(d,"css",a.B);f=a.locale||Av(b,"hl");null!=f&&_.Q(d,"hl",f);void 0!==a.Ub&&_.Q(d,
"uj",a.Ub);null!=a.R&&_.Q(d,"hpc",a.R);null!=a.aa&&_.Q(d,"hsm",a.aa);null!=a.da&&_.Q(d,"hro",a.da);null!=a.X&&_.Q(d,"hrc",a.X);null!=a.L&&_.Q(d,"hotr",a.L);null!=a.ha&&_.Q(d,"pop",a.ha);_.Q(d,"pal","1");null!=a.Jb&&_.Q(d,"uqp",a.Jb);null!=a.G&&_.Q(d,"gooa",a.G);null!=a.F&&_.Q(d,"gltsi",a.F);null!=a.Kb&&_.Q(d,"gusm",a.Kb);null!=a.silent&&_.Q(d,"sl",a.silent);a.Bc&&_.Q(d,"icr","1");a.yc&&_.Q(d,"hpl","1");a.ga&&_.Q(d,"hs",a.ga);a.fa&&_.Q(d,"dc",_.ke(a.fa.toJSON()));null!=a.Da&&_.Q(d,"molew",a.Da);null!=
a.Ba&&_.Q(d,"moleh",a.Ba);null!=a.sa&&_.Q(d,"mmoleh",a.sa);a.ye&&_.Q(d,"derp","1");a.l&&_.Q(d,"fcho",a.l);null!=a.fb&&_.Q(d,"two",a.fb);null!=a.A&&_.Q(d,"convid",a.A);_.Q(d,"host","1");_.Q(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36));this.l=d.toString()};_.F(aw,_.z);aw.prototype.install=function(a,b){bw(this,a,b,function(){})};
var bw=function(a,b,c,d){var f=a.j.getElementById(b);f||(f=a.j.createElement("div"),f.id=b,f.className=a.h.Mc,a.j.body.appendChild(f));a=(0,_.E)(function(){var g="";this.h.Ec||(g="height:400px");var h=_.qd(new _.pd(this.j),"IFRAME");_.md(h,{id:this.h.h,name:this.h.h,"class":"talk_iframe",frameborder:"0",style:g,"aria-hidden":"true",allow:"microphone *; autoplay *; microphone"});_.kd("talk_loading_msg",f)||_.od(f);f.appendChild(h);var k=this.j.getElementById(this.h.h);_.rf(this.m,k,["load","error"],
function(l){k.contentWindow.postMessage("AllowFrame: Chat","*");d(l)});k.src=this.l.toString();c()},a);window.setTimeout(a,0)};
var dw=function(){_.B.call(this);var a=this;_.x("Starting ...");this.listen(window,"unload",this.dispose);this.j=new _.Af(JSON.parse(decodeURI(location.hash.substr(1))));this.h=Dv(_.D(this.j,1));_.C(this,this.h);this.m=new _.mg;_.C(this,this.m);zv(yv(this.j).then(function(b){return cw(a,b)}),function(b){_.x("Failed to start : %s.",b||"")})},ew;_.F(dw,_.B);
var cw=function(a,b){if(!a.isDisposed()&&(a.h.sendMessage(b),_.D(b,1))){var c=new Sv,d=_.Sf(_.D(a.j,2)),f=d.j;null!=d.l&&(f+=":"+d.l);_.I(c,1,f);_.I(c,2,23);_.I(c,13,!0);_.I(c,17,!0);_.I(c,3,_.D(b,1));_.I(c,11,_.D(a.j,4));_.I(c,4,_.D(a.j,3)||"en");b=Zv(c);var g=new Xv(b,b.endpointConfig);g.j=$v(g.j,g.authUser);g.l=location.origin;g.h="gtn-roster-iframe-id-q";b=Gv(g.j,g.h);b=new aw(g,b,Date.now(),window.document);_.C(a,b);bw(b,g.xe,function(){},function(){_.rg(a.m,document.getElementById(g.h).contentWindow,
"31ACFC0_","google.com");Bv(a.m,a.h);Bv(a.h,a.m);a.h.sendMessage(new _.zf)})}};_.oc("default_host._DumpException",function(a){return console.error(a.stack)});_.fc();if(!ew||ew.isDisposed())ew=new dw;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
