on:
  push:
    branches: master

name: Update Animations
jobs:
  animator:
    if: "!contains(github.event.head_commit.message, 'autoupdate')"
    runs-on: ubuntu-latest
    steps:
      - name: Update Docs
        uses: pterm/animation-ci@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TERM: xterm-256color
