"use strict";this.default_windowbootstrap=this.default_windowbootstrap||{};(function(_){var window=this;
try{
var aa,ba,ca,da,ea,fa,ia;aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};da=ca(this);ea=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
ea("Symbol",function(a){if(a)return a;var b=function(g,h){this.h=g;ba(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.h};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,f=function(g){if(this instanceof f)throw new TypeError("b");return new b(c+(g||"")+"_"+d++,g)};return f});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});fa=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
_.n=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}};_.ha="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};if("function"==typeof Object.setPrototypeOf)ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}_.ma=ia;
ea("Promise",function(a){function b(){this.h=null}function c(h){return h instanceof f?h:new f(function(k){k(h)})}if(a)return a;b.prototype.j=function(h){if(null==this.h){this.h=[];var k=this;this.m(function(){k.o()})}this.h.push(h)};var d=da.setTimeout;b.prototype.m=function(h){d(h,0)};b.prototype.o=function(){for(;this.h&&this.h.length;){var h=this.h;this.h=[];for(var k=0;k<h.length;++k){var l=h[k];h[k]=null;try{l()}catch(m){this.l(m)}}}this.h=null};b.prototype.l=function(h){this.m(function(){throw h;
})};var f=function(h){this.h=0;this.m=void 0;this.j=[];this.v=!1;var k=this.l();try{h(k.resolve,k.reject)}catch(l){k.reject(l)}};f.prototype.l=function(){function h(m){return function(v){l||(l=!0,m.call(k,v))}}var k=this,l=!1;return{resolve:h(this.F),reject:h(this.o)}};f.prototype.F=function(h){if(h===this)this.o(new TypeError("g"));else if(h instanceof f)this.L(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;default:k=!1}k?this.N(h):this.I(h)}};f.prototype.N=
function(h){var k=void 0;try{k=h.then}catch(l){this.o(l);return}"function"==typeof k?this.R(k,h):this.I(h)};f.prototype.o=function(h){this.A(2,h)};f.prototype.I=function(h){this.A(1,h)};f.prototype.A=function(h,k){if(0!=this.h)throw Error("h`"+h+"`"+k+"`"+this.h);this.h=h;this.m=k;2===this.h&&this.G();this.B()};f.prototype.G=function(){var h=this;d(function(){if(h.fa()){var k=da.console;"undefined"!==typeof k&&k.error(h.m)}},1)};f.prototype.fa=function(){if(this.v)return!1;var h=da.CustomEvent,k=
da.Event,l=da.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof h?h=new h("unhandledrejection",{cancelable:!0}):"function"===typeof k?h=new k("unhandledrejection",{cancelable:!0}):(h=da.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.m;return l(h)};f.prototype.B=function(){if(null!=this.j){for(var h=0;h<this.j.length;++h)g.j(this.j[h]);this.j=null}};var g=new b;f.prototype.L=function(h){var k=this.l();h.Xb(k.resolve,
k.reject)};f.prototype.R=function(h,k){var l=this.l();try{h.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};f.prototype.then=function(h,k){function l(A,w){return"function"==typeof A?function(H){try{m(A(H))}catch(U){v(U)}}:w}var m,v,y=new f(function(A,w){m=A;v=w});this.Xb(l(h,m),l(k,v));return y};f.prototype.catch=function(h){return this.then(void 0,h)};f.prototype.Xb=function(h,k){function l(){switch(m.h){case 1:h(m.m);break;case 2:k(m.m);break;default:throw Error("i`"+m.h);}}var m=this;null==this.j?
g.j(l):this.j.push(l);this.v=!0};f.resolve=c;f.reject=function(h){return new f(function(k,l){l(h)})};f.race=function(h){return new f(function(k,l){for(var m=_.n(h),v=m.next();!v.done;v=m.next())c(v.value).Xb(k,l)})};f.all=function(h){var k=_.n(h),l=k.next();return l.done?c([]):new f(function(m,v){function y(H){return function(U){A[H]=U;w--;0==w&&m(A)}}var A=[],w=0;do A.push(void 0),w++,c(l.value).Xb(y(A.length-1),v),l=k.next();while(!l.done)})};return f});
ea("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var f=d.length,g=0;g<f;g++){var h=d[g];if(b.call(c,h,g,d)){b=h;break a}}b=void 0}return b}});var na=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
ea("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function d(l){if(!na(l,g)){var m=new b;ba(l,g,{value:m})}}function f(l){var m=Object[l];m&&(Object[l]=function(v){if(v instanceof b)return v;Object.isExtensible(v)&&d(v);return m(v)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),v=new a([[l,2],[m,3]]);if(2!=v.get(l)||3!=v.get(m))return!1;v.delete(l);v.set(m,4);return!v.has(l)&&4==v.get(m)}catch(y){return!1}}())return a;
var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0,k=function(l){this.h=(h+=Math.random()+1).toString();if(l){l=_.n(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};k.prototype.set=function(l,m){if(!c(l))throw Error("l");d(l);if(!na(l,g))throw Error("m`"+l);l[g][this.h]=m;return this};k.prototype.get=function(l){return c(l)&&na(l,g)?l[g][this.h]:void 0};k.prototype.has=function(l){return c(l)&&na(l,g)&&na(l[g],this.h)};k.prototype.delete=function(l){return c(l)&&
na(l,g)&&na(l[g],this.h)?delete l[g][this.h]:!1};return k});
ea("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(_.n([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),v=m.next();if(v.done||v.value[0]!=k||"s"!=v.value[1])return!1;v=m.next();return v.done||4!=v.value[0].x||"t"!=v.value[1]||!m.next().done?!1:!0}catch(y){return!1}}())return a;var b=new WeakMap,c=function(k){this.j={};this.h=
g();this.size=0;if(k){k=_.n(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.j[m.id]=[]);m.entry?m.entry.value=l:(m.entry={next:this.h,previous:this.h.previous,head:this.h,key:k,value:l},m.list.push(m.entry),this.h.previous.next=m.entry,this.h.previous=m.entry,this.size++);return this};c.prototype.delete=function(k){k=d(this,k);return k.entry&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.j[k.id],
k.entry.previous.next=k.entry.next,k.entry.next.previous=k.entry.previous,k.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.j={};this.h=this.h.previous=g();this.size=0};c.prototype.has=function(k){return!!d(this,k).entry};c.prototype.get=function(k){return(k=d(this,k).entry)&&k.value};c.prototype.entries=function(){return f(this,function(k){return[k.key,k.value]})};c.prototype.keys=function(){return f(this,function(k){return k.key})};c.prototype.values=function(){return f(this,
function(k){return k.value})};c.prototype.forEach=function(k,l){for(var m=this.entries(),v;!(v=m.next()).done;)v=v.value,k.call(l,v[1],v[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(k,l){var m=l&&typeof l;"object"==m||"function"==m?b.has(l)?m=b.get(l):(m=""+ ++h,b.set(l,m)):m="p_"+l;var v=k.j[m];if(v&&na(k.j,m))for(k=0;k<v.length;k++){var y=v[k];if(l!==l&&y.key!==y.key||l===y.key)return{id:m,list:v,index:k,entry:y}}return{id:m,list:v,index:-1,entry:void 0}},f=function(k,
l){var m=k.h;return fa(function(){if(m){for(;m.head!=k.h;)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},g=function(){var k={};return k.previous=k.next=k.head=k},h=0;return c});var oa=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,f={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f};
ea("Array.prototype.entries",function(a){return a?a:function(){return oa(this,function(b,c){return[b,c]})}});ea("Array.prototype.keys",function(a){return a?a:function(){return oa(this,function(b){return b})}});ea("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});ea("Array.prototype.values",function(a){return a?a:function(){return oa(this,function(b,c){return c})}});
ea("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var f=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var h=0;!(g=b.next()).done;)f.push(c.call(d,g.value,h++))}else for(g=b.length,h=0;h<g;h++)f.push(c.call(d,b[h],h));return f}});var pa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var f in d)na(d,f)&&(a[f]=d[f])}return a};
ea("Object.assign",function(a){return a||pa});ea("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)na(b,d)&&c.push([d,b[d]]);return c}});ea("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});ea("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var f=d.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});
ea("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("j`includes");if(b instanceof RegExp)throw new TypeError("k`includes");return-1!==this.indexOf(b,c||0)}});
ea("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(_.n([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var f=d.entries(),g=f.next();if(g.done||g.value[0]!=c||g.value[1]!=c)return!1;g=f.next();return g.done||g.value[0]==c||4!=g.value[0].x||g.value[1]!=g.value[0]?!1:f.next().done}catch(h){return!1}}())return a;var b=function(c){this.h=new Map;if(c){c=
_.n(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.h.size};b.prototype.add=function(c){c=0===c?0:c;this.h.set(c,c);this.size=this.h.size;return this};b.prototype.delete=function(c){c=this.h.delete(c);this.size=this.h.size;return c};b.prototype.clear=function(){this.h.clear();this.size=0};b.prototype.has=function(c){return this.h.has(c)};b.prototype.entries=function(){return this.h.entries()};b.prototype.values=function(){return this.h.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var f=this;this.h.forEach(function(g){return c.call(d,g,g,f)})};return b});
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.qa=_.qa||{};_.p=this||self;_.sa="closure_uid_"+(1E9*Math.random()>>>0);

}catch(e){_._DumpException(e)}
try{
_.Pg="https://support.google.com/chrome/answer/185277?hl="+chrome.i18n.getMessage("@@ui_locale");chrome.i18n.getMessage("@@ui_locale");_.Qg="https://support.google.com/hangouts/answer/6127720?hl="+chrome.i18n.getMessage("@@ui_locale");

}catch(e){_._DumpException(e)}
try{
location.search&&window.addEventListener("load",function(){chrome.runtime.getBackgroundPage(function(a){a.__onExtWindowLoad(window)})});

}catch(e){_._DumpException(e)}
}).call(this,this.default_windowbootstrap);
// Google Inc.
